# Limpieza de Datos

### Carga de Datos

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 500)

In [2]:
import sys
from pathlib import Path

# Agregar la carpeta raíz al path para poder importar
carpeta_raiz = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(carpeta_raiz))

# Importar las funciones
from funciones_save_load import guardar_parquet, cargar_parquet

# Usar las funciones
icfes = cargar_parquet("icfes_carga_inicial.parquet")
icfes.sample(6)

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,ESTU_TIENEETNIA,FAMI_ESTRATOVIVIENDA,FAMI_PERSONASHOGAR,FAMI_CUARTOSHOGAR,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,FAMI_TRABAJOLABORPADRE,FAMI_TRABAJOLABORMADRE,FAMI_TIENEINTERNET,FAMI_TIENESERVICIOTV,FAMI_TIENECOMPUTADOR,FAMI_TIENELAVADORA,FAMI_TIENEHORNOMICROOGAS,FAMI_TIENEAUTOMOVIL,FAMI_TIENEMOTOCICLETA,FAMI_TIENECONSOLAVIDEOJUEGOS,FAMI_NUMLIBROS,FAMI_COMELECHEDERIVADOS,FAMI_COMECARNEPESCADOHUEVO,FAMI_COMECEREALFRUTOSLEGUMBRE,FAMI_SITUACIONECONOMICA,ESTU_DEDICACIONLECTURADIARIA,ESTU_DEDICACIONINTERNET,ESTU_HORASSEMANATRABAJA,ESTU_TIPOREMUNERACION,COLE_GENERO,COLE_NATURALEZA,COLE_CALENDARIO,COLE_BILINGUE,COLE_CARACTER,COLE_SEDE_PRINCIPAL,COLE_AREA_UBICACION,COLE_JORNADA,ESTU_MCPIO_PRESENTACION,ESTU_DEPTO_PRESENTACION,PUNT_LECTURA_CRITICA,PUNT_MATEMATICAS,PUNT_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PUNT_INGLES,PUNT_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
287247,TI,COLOMBIA,F,2003,No,Estrato 1,3 a 4,Dos,Primaria incompleta,Primaria completa,Trabaja por cuenta propia (por ejemplo plomero...,"Trabaja en el hogar, no trabaja o estudia",Si,Si,Si,Si,No,Si,No,Si,0 A 10 LIBROS,3 a 5 veces por semana,1 o 2 veces por semana,1 o 2 veces por semana,Igual,30 minutos o menos,Entre 1 y 3 horas,0,No,MIXTO,OFICIAL,A,None,ACADÉMICO,S,URBANO,TARDE,BOGOTÁ D.C.,BOGOTÁ,55,53,57,50,47.0,266,50.430199,2.0,2.0
271673,TI,COLOMBIA,F,2003,No,Estrato 1,9 o más,Seis o mas,Secundaria (Bachillerato) completa,Primaria completa,Trabaja por cuenta propia (por ejemplo plomero...,"Trabaja en el hogar, no trabaja o estudia",No,No,No,Si,No,No,Si,No,11 A 25 LIBROS,1 o 2 veces por semana,1 o 2 veces por semana,1 o 2 veces por semana,Igual,30 minutos o menos,Entre 1 y 3 horas,0,No,MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,MAÑANA,OVEJAS,SUCRE,48,51,52,38,36.0,232,42.335647,2.0,2.0
210374,TI,COLOMBIA,M,2002,No,Estrato 3,7 a 8,Cuatro,Ninguno,Primaria incompleta,Es dueño de un negocio pequeño (tiene pocos em...,Es dueño de un negocio pequeño (tiene pocos em...,Si,Si,Si,No,Si,Si,Si,Si,0 A 10 LIBROS,Todos o casi todos los días,Todos o casi todos los días,1 o 2 veces por semana,Igual,No leo por entretenimiento,Más de 3 horas,Entre 11 y 20 horas,No,MIXTO,OFICIAL,A,None,ACADÉMICO,S,URBANO,MAÑANA,SANTA MARTA,MAGDALENA,36,25,26,37,34.0,156,54.672044,3.0,3.0
261140,TI,COLOMBIA,M,2004,No,Estrato 2,1 a 2,Dos,Primaria incompleta,Secundaria (Bachillerato) incompleta,"Es agricultor, pesquero o jornalero","Trabaja como personal de limpieza, mantenimien...",No,Si,No,No,No,No,No,Si,0 A 10 LIBROS,3 a 5 veces por semana,Todos o casi todos los días,Todos o casi todos los días,Peor,Entre 30 y 60 minutos,Más de 3 horas,0,No,MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,UNICA,FUNZA,CUNDINAMARCA,61,57,61,60,64.0,300,41.553598,2.0,3.0
109529,TI,COLOMBIA,F,2002,No,Estrato 3,1 a 2,Dos,Secundaria (Bachillerato) completa,Primaria completa,Es operario de máquinas o conduce vehículos (t...,"Trabaja en el hogar, no trabaja o estudia",Si,Si,Si,Si,Si,Si,No,No,0 A 10 LIBROS,Todos o casi todos los días,Todos o casi todos los días,Todos o casi todos los días,Igual,Entre 30 y 60 minutos,Entre 1 y 3 horas,0,No,MIXTO,NO OFICIAL,A,N,ACADÉMICO,S,URBANO,COMPLETA,BUCARAMANGA,SANTANDER,58,65,60,58,56.0,300,56.275418,3.0,3.0
184428,TI,COLOMBIA,F,2003,No,Estrato 1,3 a 4,Tres,Primaria completa,Primaria completa,Es dueño de un negocio pequeño (tiene pocos em...,"Trabaja en el hogar, no trabaja o estudia",Si,Si,Si,Si,Si,No,No,No,11 A 25 LIBROS,3 a 5 veces por semana,Todos o casi todos los días,1 o 2 veces por semana,Igual,No leo por entretenimiento,Entre 1 y 3 horas,Entre 11 y 20 horas,"Si, en efectivo",MIXTO,NO OFICIAL,A,N,ACADÉMICO,S,URBANO,UNICA,SABANAGRANDE,ATLANTICO,70,82,79,76,69.0,381,51.536175,3.0,2.0

### 1. Renombrar Variables

In [3]:
icfes.sample(5)

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,ESTU_TIENEETNIA,FAMI_ESTRATOVIVIENDA,FAMI_PERSONASHOGAR,FAMI_CUARTOSHOGAR,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,FAMI_TRABAJOLABORPADRE,FAMI_TRABAJOLABORMADRE,FAMI_TIENEINTERNET,FAMI_TIENESERVICIOTV,FAMI_TIENECOMPUTADOR,FAMI_TIENELAVADORA,FAMI_TIENEHORNOMICROOGAS,FAMI_TIENEAUTOMOVIL,FAMI_TIENEMOTOCICLETA,FAMI_TIENECONSOLAVIDEOJUEGOS,FAMI_NUMLIBROS,FAMI_COMELECHEDERIVADOS,FAMI_COMECARNEPESCADOHUEVO,FAMI_COMECEREALFRUTOSLEGUMBRE,FAMI_SITUACIONECONOMICA,ESTU_DEDICACIONLECTURADIARIA,ESTU_DEDICACIONINTERNET,ESTU_HORASSEMANATRABAJA,ESTU_TIPOREMUNERACION,COLE_GENERO,COLE_NATURALEZA,COLE_CALENDARIO,COLE_BILINGUE,COLE_CARACTER,COLE_SEDE_PRINCIPAL,COLE_AREA_UBICACION,COLE_JORNADA,ESTU_MCPIO_PRESENTACION,ESTU_DEPTO_PRESENTACION,PUNT_LECTURA_CRITICA,PUNT_MATEMATICAS,PUNT_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PUNT_INGLES,PUNT_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO
498284,TI,COLOMBIA,M,2003,No,Estrato 3,3 a 4,Tres,Técnica o tecnológica incompleta,Secundaria (Bachillerato) completa,"Trabaja en el hogar, no trabaja o estudia",Trabaja por cuenta propia (por ejemplo plomero...,Si,Si,Si,Si,Si,No,No,Si,0 A 10 LIBROS,Todos o casi todos los días,3 a 5 veces por semana,1 o 2 veces por semana,Igual,No leo por entretenimiento,Más de 3 horas,0,No,MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,UNICA,BOGOTÁ D.C.,BOGOTÁ,49,56,48,34,42.0,232,56.254817,3.0,3.0
43901,TI,COLOMBIA,M,2004,No,Estrato 2,3 a 4,Tres,Primaria completa,Primaria completa,Es dueño de un negocio pequeño (tiene pocos em...,Es dueño de un negocio pequeño (tiene pocos em...,Si,Si,Si,Si,No,No,No,No,26 A 100 LIBROS,1 o 2 veces por semana,1 o 2 veces por semana,3 a 5 veces por semana,Igual,Entre 30 y 60 minutos,30 minutos o menos,Menos de 10 horas,"Si, en efectivo",MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,MAÑANA,FLORENCIA,CAQUETA,61,64,63,58,60.0,307,50.277335,2.0,2.0
61350,TI,COLOMBIA,F,2003,No,Estrato 3,3 a 4,Tres,No sabe,Técnica o tecnológica completa,No sabe,Tiene un trabajo de tipo auxiliar administrati...,Si,Si,Si,No,Si,No,Si,Si,11 A 25 LIBROS,3 a 5 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Mejor,Entre 30 y 60 minutos,30 minutos o menos,0,No,MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,MAÑANA,PIEDECUESTA,SANTANDER,68,61,57,58,55.0,303,56.324889,3.0,3.0
82366,TI,COLOMBIA,M,2003,No,Estrato 1,3 a 4,Tres,Secundaria (Bachillerato) incompleta,Educación profesional completa,Trabaja por cuenta propia (por ejemplo plomero...,"Trabaja como profesional (por ejemplo médico, ...",Si,No,No,Si,No,No,No,No,11 A 25 LIBROS,Nunca o rara vez comemos eso,3 a 5 veces por semana,1 o 2 veces por semana,Igual,Entre 30 y 60 minutos,Entre 30 y 60 minutos,0,No,MIXTO,OFICIAL,A,N,TÉCNICO,S,URBANO,MAÑANA,CARTAGO,VALLE,63,73,60,51,49.0,304,48.913311,2.0,3.0
243500,TI,COLOMBIA,F,2003,No,Estrato 3,5 a 6,Cuatro,Educación profesional completa,Educación profesional completa,"Trabaja como profesional (por ejemplo médico, ...","Trabaja como profesional (por ejemplo médico, ...",Si,No,Si,Si,Si,No,No,No,MÁS DE 100 LIBROS,Todos o casi todos los días,Todos o casi todos los días,Todos o casi todos los días,Peor,Entre 1 y 2 horas,Más de 3 horas,0,No,MIXTO,NO OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,COMPLETA,BOGOTÁ D.C.,BOGOTÁ,66,61,59,70,71.0,323,68.959544,4.0,3.0

In [4]:
icfes.columns

Index(['ESTU_TIPODOCUMENTO', 'ESTU_NACIONALIDAD', 'ESTU_GENERO',
       'ESTU_FECHANACIMIENTO', 'ESTU_TIENEETNIA', 'FAMI_ESTRATOVIVIENDA',
       'FAMI_PERSONASHOGAR', 'FAMI_CUARTOSHOGAR', 'FAMI_EDUCACIONPADRE',
       'FAMI_EDUCACIONMADRE', 'FAMI_TRABAJOLABORPADRE',
       'FAMI_TRABAJOLABORMADRE', 'FAMI_TIENEINTERNET', 'FAMI_TIENESERVICIOTV',
       'FAMI_TIENECOMPUTADOR', 'FAMI_TIENELAVADORA',
       'FAMI_TIENEHORNOMICROOGAS', 'FAMI_TIENEAUTOMOVIL',
       'FAMI_TIENEMOTOCICLETA', 'FAMI_TIENECONSOLAVIDEOJUEGOS',
       'FAMI_NUMLIBROS', 'FAMI_COMELECHEDERIVADOS',
       'FAMI_COMECARNEPESCADOHUEVO', 'FAMI_COMECEREALFRUTOSLEGUMBRE',
       'FAMI_SITUACIONECONOMICA', 'ESTU_DEDICACIONLECTURADIARIA',
       'ESTU_DEDICACIONINTERNET', 'ESTU_HORASSEMANATRABAJA',
       'ESTU_TIPOREMUNERACION', 'COLE_GENERO', 'COLE_NATURALEZA',
       'COLE_CALENDARIO', 'COLE_BILINGUE', 'COLE_CARACTER',
       'COLE_SEDE_PRINCIPAL', 'COLE_AREA_UBICACION', 'COLE_JORNADA',
       'ESTU_MCPIO_PRESENTACION', 'ESTU_DEPTO_PRESENTACION',
       'PUNT_LECTURA_CRITICA', 'PUNT_MATEMATICAS', 'PUNT_C_NATURALES',
       'PUNT_SOCIALES_CIUDADANAS', 'PUNT_INGLES', 'PUNT_GLOBAL',
       'ESTU_INSE_INDIVIDUAL', 'ESTU_NSE_INDIVIDUAL',
       'ESTU_NSE_ESTABLECIMIENTO'],
      dtype='object')

In [5]:
icfes.rename(columns= {
    'ESTU_TIPODOCUMENTO': 'tipo_documento',
    'ESTU_NACIONALIDAD': 'nacionalidad',
    'ESTU_GENERO': 'genero',
    'ESTU_FECHANACIMIENTO': 'anio_nacimiento',
    'ESTU_TIENEETNIA': 'pertenece_etnia',
    'FAMI_ESTRATOVIVIENDA': 'estrato_casa',
    'FAMI_PERSONASHOGAR': 'num_personas_casa', 
    'FAMI_CUARTOSHOGAR': 'cuartos_casa', 
    'FAMI_EDUCACIONPADRE': 'educacion_padre',
    'FAMI_EDUCACIONMADRE': 'educacion_madre', 
    'FAMI_TRABAJOLABORPADRE': 'actividad_padre',
    'FAMI_TRABAJOLABORMADRE': 'actividad_madre', 
    'FAMI_TIENEINTERNET': 'internet', 
    'FAMI_TIENESERVICIOTV': 'tv',
    'FAMI_TIENECOMPUTADOR': 'computador', 
    'FAMI_TIENELAVADORA': 'lavadora',
    'FAMI_TIENEHORNOMICROOGAS': 'microndas', 
    'FAMI_TIENEAUTOMOVIL': 'carro',
    'FAMI_TIENEMOTOCICLETA': 'moto', 
    'FAMI_TIENECONSOLAVIDEOJUEGOS': 'consola',
    'FAMI_NUMLIBROS': 'num_libros_casa', 
    'FAMI_COMELECHEDERIVADOS': 'come_derivados_leche',
    'FAMI_COMECARNEPESCADOHUEVO': 'come_carne_pescado_huevo', 
    'FAMI_COMECEREALFRUTOSLEGUMBRE': 'come_cereal_frutas_legumbres',
    'FAMI_SITUACIONECONOMICA': 'situacion_economica', 
    'ESTU_DEDICACIONLECTURADIARIA': 'cuanto_lee',
    'ESTU_DEDICACIONINTERNET': 'cuanto_navega_web', 
    'ESTU_HORASSEMANATRABAJA': 'horas_trabajo_semanal',
    'ESTU_TIPOREMUNERACION': 'tipo_pago_trabajo', 
    'COLE_GENERO': 'colegio_genero', 
    'COLE_NATURALEZA': 'colegio_oficial',
    'COLE_CALENDARIO': 'colegio_calendario', 
    'COLE_BILINGUE': 'colegio_bilingue', 
    'COLE_CARACTER': 'tipo_colegio',
    'COLE_SEDE_PRINCIPAL': 'colegio_sede_principal', 
    'COLE_AREA_UBICACION': 'colegio_urbano_rural', 
    'COLE_JORNADA': 'colegio_jornada',
    'ESTU_MCPIO_PRESENTACION': 'mpio_colegio', 
    'ESTU_DEPTO_PRESENTACION': 'dpto_colegio',
    'PUNT_LECTURA_CRITICA': 'puntaje_lectura', 
    'PUNT_MATEMATICAS': 'puntaje_matematicas', 
    'PUNT_C_NATURALES': 'puntaje_naturales',  
    'PUNT_SOCIALES_CIUDADANAS': 'puntaje_sociales',
    'PUNT_INGLES': 'puntaje_ingles', 
    'PUNT_GLOBAL': 'puntaje_global',
    'ESTU_INSE_INDIVIDUAL': 'inse_estudiante', 
    'ESTU_NSE_INDIVIDUAL': 'nse_estudiantes',
    'ESTU_NSE_ESTABLECIMIENTO': 'nse_colegio'
}, inplace=True)

icfes.sample(6)

,tipo_documento,nacionalidad,genero,anio_nacimiento,pertenece_etnia,estrato_casa,num_personas_casa,cuartos_casa,educacion_padre,educacion_madre,actividad_padre,actividad_madre,internet,tv,computador,lavadora,microndas,carro,moto,consola,num_libros_casa,come_derivados_leche,come_carne_pescado_huevo,come_cereal_frutas_legumbres,situacion_economica,cuanto_lee,cuanto_navega_web,horas_trabajo_semanal,tipo_pago_trabajo,colegio_genero,colegio_oficial,colegio_calendario,colegio_bilingue,tipo_colegio,colegio_sede_principal,colegio_urbano_rural,colegio_jornada,mpio_colegio,dpto_colegio,puntaje_lectura,puntaje_matematicas,puntaje_naturales,puntaje_sociales,puntaje_ingles,puntaje_global,inse_estudiante,nse_estudiantes,nse_colegio
309355,TI,COLOMBIA,M,2004,No,Estrato 2,5 a 6,Cuatro,Educación profesional incompleta,Educación profesional incompleta,Pensionado,Es dueño de un negocio pequeño (tiene pocos em...,Si,Si,Si,Si,Si,No,Si,No,26 A 100 LIBROS,Todos o casi todos los días,Todos o casi todos los días,Todos o casi todos los días,Mejor,Entre 30 y 60 minutos,Más de 3 horas,0,No,MIXTO,NO OFICIAL,A,N,ACADÉMICO,S,URBANO,COMPLETA,SOGAMOSO,BOYACA,65,67,67,66,56.0,327,65.258644,4.0,3.0
176047,TI,COLOMBIA,F,2005,No,Estrato 2,7 a 8,Tres,Técnica o tecnológica completa,Secundaria (Bachillerato) completa,"Trabaja en el hogar, no trabaja o estudia","Trabaja en el hogar, no trabaja o estudia",Si,No,No,Si,No,No,No,No,11 A 25 LIBROS,1 o 2 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Igual,Entre 30 y 60 minutos,Entre 1 y 3 horas,0,No,MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,TARDE,CARTAGENA DE INDIAS,BOLIVAR,63,64,66,66,61.0,322,47.270269,2.0,2.0
101270,TI,COLOMBIA,F,2002,No,Estrato 2,5 a 6,Tres,Primaria completa,Primaria completa,Es dueño de un negocio pequeño (tiene pocos em...,"Trabaja en el hogar, no trabaja o estudia",No,Si,No,No,No,No,No,No,0 A 10 LIBROS,1 o 2 veces por semana,3 a 5 veces por semana,3 a 5 veces por semana,Igual,Entre 1 y 2 horas,No Navega Internet,Menos de 10 horas,No,MIXTO,OFICIAL,A,None,ACADÉMICO,S,RURAL,COMPLETA,PITALITO,HUILA,47,48,46,45,36.0,228,41.297979,2.0,2.0
89053,TI,COLOMBIA,F,2004,No,Estrato 2,5 a 6,Cuatro,Secundaria (Bachillerato) completa,Técnica o tecnológica completa,"Trabaja como profesional (por ejemplo médico, ...","Trabaja como profesional (por ejemplo médico, ...",Si,Si,Si,Si,No,Si,Si,No,11 A 25 LIBROS,1 o 2 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Igual,Entre 30 y 60 minutos,Más de 3 horas,Entre 11 y 20 horas,"Si, en efectivo",MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,UNICA,EL PAUJÍL,CAQUETA,46,49,50,40,44.0,230,57.051494,3.0,2.0
336490,TI,COLOMBIA,M,2002,No,Estrato 1,5 a 6,Cuatro,Educación profesional completa,Educación profesional completa,"Trabaja como profesional (por ejemplo médico, ...","Trabaja como profesional (por ejemplo médico, ...",Si,Si,Si,Si,Si,No,No,No,0 A 10 LIBROS,Todos o casi todos los días,Todos o casi todos los días,Todos o casi todos los días,Mejor,Entre 30 y 60 minutos,Más de 3 horas,Menos de 10 horas,"Si, en efectivo",MIXTO,OFICIAL,A,None,ACADÉMICO,S,URBANO,MAÑANA,BARRANQUILLA,ATLANTICO,48,44,48,47,44.0,233,66.548142,4.0,2.0
411601,TI,COLOMBIA,F,2003,No,Estrato 2,3 a 4,Tres,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) completa,Es operario de máquinas o conduce vehículos (t...,"Trabaja en el hogar, no trabaja o estudia",No,No,Si,Si,No,Si,No,No,11 A 25 LIBROS,1 o 2 veces por semana,Todos o casi todos los días,1 o 2 veces por semana,Peor,Entre 30 y 60 minutos,Entre 30 y 60 minutos,0,No,MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,MAÑANA,PAIPA,BOYACA,68,62,63,60,47.0,310,48.383000,2.0,2.0

### 2. Duplicados

In [6]:
print(f"Total de filas duplicadas: {icfes.duplicated().sum()}")

Total de filas duplicadas: 2

In [7]:
duplicados = icfes[icfes.duplicated(keep=False)]  # keep=False muestra TODAS las copias
print(f"Hay {len(duplicados):,} filas que aparecen duplicadas (contando todas las copias)")

# Ver las primeras 10
duplicados.head(10)

Hay 4 filas que aparecen duplicadas (contando todas las copias)

,tipo_documento,nacionalidad,genero,anio_nacimiento,pertenece_etnia,estrato_casa,num_personas_casa,cuartos_casa,educacion_padre,educacion_madre,actividad_padre,actividad_madre,internet,tv,computador,lavadora,microndas,carro,moto,consola,num_libros_casa,come_derivados_leche,come_carne_pescado_huevo,come_cereal_frutas_legumbres,situacion_economica,cuanto_lee,cuanto_navega_web,horas_trabajo_semanal,tipo_pago_trabajo,colegio_genero,colegio_oficial,colegio_calendario,colegio_bilingue,tipo_colegio,colegio_sede_principal,colegio_urbano_rural,colegio_jornada,mpio_colegio,dpto_colegio,puntaje_lectura,puntaje_matematicas,puntaje_naturales,puntaje_sociales,puntaje_ingles,puntaje_global,inse_estudiante,nse_estudiantes,nse_colegio
367644,TI,COLOMBIA,M,2003,No,Estrato 2,3 a 4,Dos,Secundaria (Bachillerato) completa,Técnica o tecnológica completa,"Trabaja como personal de limpieza, mantenimien...",Tiene un trabajo de tipo auxiliar administrati...,Si,Si,Si,Si,No,No,No,No,11 A 25 LIBROS,1 o 2 veces por semana,1 o 2 veces por semana,Nunca o rara vez comemos eso,Peor,30 minutos o menos,Entre 30 y 60 minutos,Menos de 10 horas,"Si, en efectivo",MIXTO,OFICIAL,A,None,ACADÉMICO,S,URBANO,MAÑANA,BOGOTÁ D.C.,BOGOTÁ,50,62,53,49,56.0,268,50.308181,2.0,3.0
422598,TI,COLOMBIA,M,2002,No,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,NOCHE,MEDELLÍN,ANTIOQUIA,0,0,0,26,0.0,30,NaN,NaN,2.0
422608,TI,COLOMBIA,M,2002,No,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,NOCHE,MEDELLÍN,ANTIOQUIA,0,0,0,26,0.0,30,NaN,NaN,2.0
426786,TI,COLOMBIA,M,2003,No,Estrato 2,3 a 4,Dos,Secundaria (Bachillerato) completa,Técnica o tecnológica completa,"Trabaja como personal de limpieza, mantenimien...",Tiene un trabajo de tipo auxiliar administrati...,Si,Si,Si,Si,No,No,No,No,11 A 25 LIBROS,1 o 2 veces por semana,1 o 2 veces por semana,Nunca o rara vez comemos eso,Peor,30 minutos o menos,Entre 30 y 60 minutos,Menos de 10 horas,"Si, en efectivo",MIXTO,OFICIAL,A,None,ACADÉMICO,S,URBANO,MAÑANA,BOGOTÁ D.C.,BOGOTÁ,50,62,53,49,56.0,268,50.308181,2.0,3.0

In [8]:
icfes = icfes.drop_duplicates()
print(f"Total de filas duplicadas: {icfes.duplicated().sum()}")

Total de filas duplicadas: 0

### 3. Rango de valores válidos

In [9]:
icfes.sample(6)

,tipo_documento,nacionalidad,genero,anio_nacimiento,pertenece_etnia,estrato_casa,num_personas_casa,cuartos_casa,educacion_padre,educacion_madre,actividad_padre,actividad_madre,internet,tv,computador,lavadora,microndas,carro,moto,consola,num_libros_casa,come_derivados_leche,come_carne_pescado_huevo,come_cereal_frutas_legumbres,situacion_economica,cuanto_lee,cuanto_navega_web,horas_trabajo_semanal,tipo_pago_trabajo,colegio_genero,colegio_oficial,colegio_calendario,colegio_bilingue,tipo_colegio,colegio_sede_principal,colegio_urbano_rural,colegio_jornada,mpio_colegio,dpto_colegio,puntaje_lectura,puntaje_matematicas,puntaje_naturales,puntaje_sociales,puntaje_ingles,puntaje_global,inse_estudiante,nse_estudiantes,nse_colegio
199864,TI,COLOMBIA,F,2005,No,Sin Estrato,5 a 6,Dos,Primaria incompleta,Primaria incompleta,"Es agricultor, pesquero o jornalero","Es agricultor, pesquero o jornalero",No,Si,No,No,No,No,Si,No,0 A 10 LIBROS,1 o 2 veces por semana,1 o 2 veces por semana,1 o 2 veces por semana,Peor,Entre 1 y 2 horas,Entre 30 y 60 minutos,0,No,MIXTO,OFICIAL,A,N,ACADÉMICO,S,RURAL,MAÑANA,SAN ANDRÉS DE TUMACO,NARIÑO,62,53,49,53,39.0,265,31.292483,1.0,2.0
321858,TI,COLOMBIA,F,2003,No,Estrato 2,5 a 6,Tres,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) completa,Trabaja por cuenta propia (por ejemplo plomero...,"Trabaja en el hogar, no trabaja o estudia",Si,Si,No,Si,Si,No,No,No,0 A 10 LIBROS,3 a 5 veces por semana,Todos o casi todos los días,1 o 2 veces por semana,Mejor,30 minutos o menos,Más de 3 horas,Entre 11 y 20 horas,"Si, en efectivo",MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,UNICA,CALI,VALLE,57,56,55,56,52.0,278,49.388846,2.0,2.0
430194,TI,COLOMBIA,F,2002,No,Estrato 2,3 a 4,Tres,No Aplica,Técnica o tecnológica completa,Es dueño de un negocio pequeño (tiene pocos em...,Es vendedor o trabaja en atención al público,Si,Si,Si,Si,No,No,No,No,11 A 25 LIBROS,1 o 2 veces por semana,3 a 5 veces por semana,Todos o casi todos los días,Peor,30 minutos o menos,Más de 3 horas,0,No,MIXTO,NO OFICIAL,OTRO,None,ACADÉMICO,S,URBANO,SABATINA,MEDELLÍN,ANTIOQUIA,64,36,47,50,57.0,249,55.671880,3.0,3.0
330227,TI,COLOMBIA,M,2004,No,Estrato 3,7 a 8,None,Educación profesional completa,Educación profesional completa,Es vendedor o trabaja en atención al público,Es vendedor o trabaja en atención al público,Si,Si,Si,Si,No,Si,No,Si,26 A 100 LIBROS,1 o 2 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Mejor,30 minutos o menos,Más de 3 horas,Entre 11 y 20 horas,"Si, en especie",MIXTO,NO OFICIAL,A,N,ACADÉMICO,S,URBANO,COMPLETA,SOACHA,CUNDINAMARCA,58,58,44,46,42.0,254,59.860633,3.0,3.0
156990,TI,COLOMBIA,F,2002,No,Estrato 1,3 a 4,Dos,Primaria incompleta,Técnica o tecnológica incompleta,Es vendedor o trabaja en atención al público,"Trabaja en el hogar, no trabaja o estudia",No,No,No,No,Si,No,Si,No,0 A 10 LIBROS,1 o 2 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Igual,30 minutos o menos,30 minutos o menos,0,No,MIXTO,OFICIAL,A,None,TÉCNICO/ACADÉMICO,S,URBANO,UNICA,CÚCUTA,NORTE SANTANDER,42,47,44,39,28.0,209,42.018709,2.0,2.0
279697,TI,COLOMBIA,M,2003,No,Estrato 1,5 a 6,Dos,No Aplica,Secundaria (Bachillerato) completa,"Es agricultor, pesquero o jornalero","Trabaja en el hogar, no trabaja o estudia",No,Si,No,Si,No,No,No,No,11 A 25 LIBROS,1 o 2 veces por semana,1 o 2 veces por semana,Nunca o rara vez comemos eso,Igual,30 minutos o menos,Entre 1 y 3 horas,Entre 11 y 20 horas,No,MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,MAÑANA,FUNDACIÓN,MAGDALENA,51,32,41,31,35.0,192,39.177180,1.0,2.0

In [10]:
cat_vars = icfes.select_dtypes(include='object')

for col in cat_vars.columns:
    print(icfes[col].value_counts().sort_index().head(15))   # o .head(20)
    print("-" * 60)

tipo_documento
CC       83373
CE        1096
CR        4923
NES       1454
NUIP         2
PC           3
PE          74
PEP        417
RC          14
TI      413512
V            2
Name: count, dtype: int64
------------------------------------------------------------
nacionalidad
ALEMANIA                1
ARABIA SAUDITA          1
ARGENTINA               8
ARUBA                   1
BOLIVIA                 3
BRASIL                  8
CABO VERDE              2
CANADÁ                  1
CHILE                   3
CHINA                   2
COLOMBIA           501706
COREA DEL NORTE         1
COREA DEL SUR           3
COSTA RICA              7
CUBA                    9
Name: count, dtype: int64
------------------------------------------------------------
genero
F    276572
M    228290
Name: count, dtype: int64
------------------------------------------------------------
pertenece_etnia
No    469936
Si     31941
Name: count, dtype: int64
------------------------------------------------------------
estrato_casa
Estrato 1      152852
Estrato 2      182321
Estrato 3      103550
Estrato 4       23463
Estrato 5        7019
Estrato 6        3083
Sin Estrato     15631
Name: count, dtype: int64
------------------------------------------------------------
num_personas_casa
1 a 2       36691
3 a 4      240081
5 a 6      155486
7 a 8       41144
9 o más     16296
Name: count, dtype: int64
------------------------------------------------------------
cuartos_casa
Cinco          22927
Cuatro         67233
Dos           171074
Seis o mas     13108
Tres          189410
Uno            25280
Name: count, dtype: int64
------------------------------------------------------------
educacion_padre
Educación profesional completa           46737
Educación profesional incompleta         10231
Ninguno                                  20798
No Aplica                                 7735
No sabe                                  29872
Postgrado                                 9568
Primaria completa                        45931
Primaria incompleta                      92089
Secundaria (Bachillerato) completa      120321
Secundaria (Bachillerato) incompleta     65305
Técnica o tecnológica completa           33073
Técnica o tecnológica incompleta         10221
Name: count, dtype: int64
------------------------------------------------------------
educacion_madre
Educación profesional completa           56344
Educación profesional incompleta         12621
Ninguno                                  12363
No Aplica                                 1170
No sabe                                   8859
Postgrado                                11239
Primaria completa                        45987
Primaria incompleta                      71289
Secundaria (Bachillerato) completa      137647
Secundaria (Bachillerato) incompleta     68181
Técnica o tecnológica completa           50487
Técnica o tecnológica incompleta         15198
Name: count, dtype: int64
------------------------------------------------------------
actividad_padre
Es agricultor, pesquero o jornalero                                                                     67182
Es dueño de un negocio grande, tiene un cargo de nivel directivo o gerencial                            13254
Es dueño de un negocio pequeño (tiene pocos empleados o no tiene, por ejemplo tienda, papelería, etc    87134
Es operario de máquinas o conduce vehículos (taxita, chofer)                                            47202
Es vendedor o trabaja en atención al público                                                            30960
No sabe                                                                                                 44958
Pensionado                                                                                              13122
Tiene un trabajo de tipo auxiliar administrativo (por ejemplo, secretario o asistente)                  21536
Trabaja como personal de limpieza, mantenimiento, seguridad o construcción                              33059
Trabaja como profesional (por ejemplo médico, abogado, ingeniero)                                       37575
Trabaja en el hogar, no trabaja o estudia                                                               32105
Trabaja por cuenta propia (por ejemplo plomero, electricista)                                           57093
Name: count, dtype: int64
------------------------------------------------------------
actividad_madre
Es agricultor, pesquero o jornalero                                                                      15991
Es dueño de un negocio grande, tiene un cargo de nivel directivo o gerencial                              9516
Es dueño de un negocio pequeño (tiene pocos empleados o no tiene, por ejemplo tienda, papelería, etc     73718
Es operario de máquinas o conduce vehículos (taxita, chofer)                                              7754
Es vendedor o trabaja en atención al público                                                             38526
No sabe                                                                                                  13383
Pensionado                                                                                                3623
Tiene un trabajo de tipo auxiliar administrativo (por ejemplo, secretario o asistente)                   38235
Trabaja como personal de limpieza, mantenimiento, seguridad o construcción                               40669
Trabaja como profesional (por ejemplo médico, abogado, ingeniero)                                        40346
Trabaja en el hogar, no trabaja o estudia                                                               188123
Trabaja por cuenta propia (por ejemplo plomero, electricista)                                            17388
Name: count, dtype: int64
------------------------------------------------------------
internet
No    148382
Si    342824
Name: count, dtype: int64
------------------------------------------------------------
tv
No    123949
Si    365483
Name: count, dtype: int64
------------------------------------------------------------
computador
No    191168
Si    293509
Name: count, dtype: int64
------------------------------------------------------------
lavadora
No    106860
Si    381779
Name: count, dtype: int64
------------------------------------------------------------
microndas
No    257541
Si    230188
Name: count, dtype: int64
------------------------------------------------------------
carro
No    360568
Si    126494
Name: count, dtype: int64
------------------------------------------------------------
moto
No    275199
Si    212586
Name: count, dtype: int64
------------------------------------------------------------
consola
No    382239
Si    105154
Name: count, dtype: int64
------------------------------------------------------------
num_libros_casa
0 A 10 LIBROS        206842
11 A 25 LIBROS       151930
26 A 100 LIBROS      100651
MÁS DE 100 LIBROS     31605
Name: count, dtype: int64
------------------------------------------------------------
come_derivados_leche
1 o 2 veces por semana          172301
3 a 5 veces por semana          129050
Nunca o rara vez comemos eso     48143
Todos o casi todos los días     141749
Name: count, dtype: int64
------------------------------------------------------------
come_carne_pescado_huevo
1 o 2 veces por semana          121466
3 a 5 veces por semana          151574
Nunca o rara vez comemos eso     21767
Todos o casi todos los días     194758
Name: count, dtype: int64
------------------------------------------------------------
come_cereal_frutas_legumbres
1 o 2 veces por semana          195093
3 a 5 veces por semana          141872
Nunca o rara vez comemos eso     74112
Todos o casi todos los días      73531
Name: count, dtype: int64
------------------------------------------------------------
situacion_economica
Igual    291475
Mejor     87943
Peor     109139
Name: count, dtype: int64
------------------------------------------------------------
cuanto_lee
30 minutos o menos            189388
Entre 1 y 2 horas              51076
Entre 30 y 60 minutos         132538
Más de 2 horas                 21736
No leo por entretenimiento     95652
Name: count, dtype: int64
------------------------------------------------------------
cuanto_navega_web
30 minutos o menos        66563
Entre 1 y 3 horas        150557
Entre 30 y 60 minutos    109722
Más de 3 horas           134493
No Navega Internet        28910
Name: count, dtype: int64
------------------------------------------------------------
horas_trabajo_semanal
0                      293827
Entre 11 y 20 horas     51044
Entre 21 y 30 horas     21609
Menos de 10 horas       95286
Más de 30 horas         26121
Name: count, dtype: int64
------------------------------------------------------------
tipo_pago_trabajo
No                           324731
Si, en efectivo              141637
Si, en efectivo y especie      9473
Si, en especie                11384
Name: count, dtype: int64
------------------------------------------------------------
colegio_genero
FEMENINO      12729
MASCULINO      3979
MIXTO        488162
Name: count, dtype: int64
------------------------------------------------------------
colegio_oficial
NO OFICIAL    113402
OFICIAL       391468
Name: count, dtype: int64
------------------------------------------------------------
colegio_calendario
A       502691
B          375
OTRO      1804
Name: count, dtype: int64
------------------------------------------------------------
colegio_bilingue
N    416665
S      5199
Name: count, dtype: int64
------------------------------------------------------------
tipo_colegio
ACADÉMICO            259425
NO APLICA              6862
TÉCNICO               55255
TÉCNICO/ACADÉMICO    169151
Name: count, dtype: int64
------------------------------------------------------------
colegio_sede_principal
N     24039
S    480831
Name: count, dtype: int64
------------------------------------------------------------
colegio_urbano_rural
RURAL      82894
URBANO    421976
Name: count, dtype: int64
------------------------------------------------------------
colegio_jornada
COMPLETA     77513
MAÑANA      200582
NOCHE        20620
SABATINA     25140
TARDE        48826
UNICA       132189
Name: count, dtype: int64
------------------------------------------------------------
mpio_colegio
ABEJORRAL           195
ACACÍAS            1647
ACANDÍ               87
ACHÍ                342
AGUACHICA          1521
AGUADAS             231
AGUAZUL             482
AGUSTÍN CODAZZI     540
AIPE                128
ALBANIA             207
ALBÁN               480
ALCALÁ              207
ALMAGUER            112
ALTO BAUDÓ           67
AMAGÁ               700
Name: count, dtype: int64
------------------------------------------------------------
dpto_colegio
AMAZONAS          631
ANTIOQUIA       70526
ARAUCA           3110
ATLANTICO       29228
BOGOTÁ          77470
BOLIVAR         23125
BOYACA          15400
CALDAS          10250
CAQUETA          3950
CASANARE         5627
CAUCA           12241
CESAR           12724
CHOCO            4248
CORDOBA         19315
CUNDINAMARCA    33280
Name: count, dtype: int64
------------------------------------------------------------

In [11]:
num_vars = icfes.select_dtypes(include=('int64', 'float'))

for col in num_vars:
    print(icfes[col].value_counts().sort_index().head(15))
    print("=" * 60)

anio_nacimiento
1        3
2        4
3        5
4        2
1195     1
1900    13
1939     1
1940     1
1941     1
1944     1
1945     2
1946     2
1947     1
1948     4
1949     2
Name: count, dtype: int64
============================================================
puntaje_lectura
0      196
22      10
23      30
24      97
25     157
26     318
27     536
28     779
29    1211
30    1738
31    2289
32    3073
33    3808
34    4868
35    5891
Name: count, dtype: int64
============================================================
puntaje_matematicas
0      182
17      25
18      84
19     155
20     265
21     390
22     573
23     721
24     932
25    1212
26    1531
27    1983
28    2324
29    2814
30    3468
Name: count, dtype: int64
============================================================
puntaje_naturales
0       391
23        1
24      101
25      432
26      841
27     1357
28     2200
29     3265
30     4478
31     6021
32     7483
33     8891
34    10164
35    11810
36    12802
Name: count, dtype: int64
============================================================
puntaje_sociales
0      190
19       1
20     106
21     255
22     436
23     710
24    1135
25    1742
26    2361
27    3159
28    4097
29    5278
30    6535
31    7785
32    9166
Name: count, dtype: int64
============================================================
puntaje_ingles
0.0      1281
28.0      964
29.0     2312
30.0     4603
31.0     6461
32.0     8306
33.0    10656
34.0    12804
35.0    14459
36.0    16398
37.0    17666
38.0    19086
39.0    19904
40.0    20766
41.0    21308
Name: count, dtype: int64
============================================================
puntaje_global
0     80
11     2
12     3
20     2
21     4
22     2
23     7
24     8
25     7
26     1
27     7
28    14
29     8
30     3
32     5
Name: count, dtype: int64
============================================================
inse_estudiante
14.281577    1
14.346915    1
14.491657    1
14.961835    1
15.317967    2
16.102877    1
16.166103    1
16.187420    1
16.517336    2
16.579543    1
16.612989    1
16.859336    1
16.876211    1
16.879373    1
16.894137    1
Name: count, dtype: int64
============================================================
nse_estudiantes
1.0     75349
2.0    181585
3.0    192877
4.0     41115
Name: count, dtype: int64
============================================================
nse_colegio
1.0     25208
2.0    261345
3.0    194860
4.0     23408
Name: count, dtype: int64
============================================================

#### Corrigiendo los años de nacimiento

In [12]:
icfes['anio_nacimiento'].value_counts(dropna=False).sort_index()

anio_nacimiento
1        3
2        4
3        5
4        2
1195     1
        ..
2014     8
2015     3
2018     2
2019     3
2020    80
Name: count, Length: 84, dtype: int64

In [13]:
icfes[(icfes['anio_nacimiento'] < 1939) | (icfes['anio_nacimiento'] > 2006)]

,tipo_documento,nacionalidad,genero,anio_nacimiento,pertenece_etnia,estrato_casa,num_personas_casa,cuartos_casa,educacion_padre,educacion_madre,actividad_padre,actividad_madre,internet,tv,computador,lavadora,microndas,carro,moto,consola,num_libros_casa,come_derivados_leche,come_carne_pescado_huevo,come_cereal_frutas_legumbres,situacion_economica,cuanto_lee,cuanto_navega_web,horas_trabajo_semanal,tipo_pago_trabajo,colegio_genero,colegio_oficial,colegio_calendario,colegio_bilingue,tipo_colegio,colegio_sede_principal,colegio_urbano_rural,colegio_jornada,mpio_colegio,dpto_colegio,puntaje_lectura,puntaje_matematicas,puntaje_naturales,puntaje_sociales,puntaje_ingles,puntaje_global,inse_estudiante,nse_estudiantes,nse_colegio
1284,PEP,VENEZUELA,M,2013,No,Estrato 4,3 a 4,Dos,No sabe,No sabe,"Es dueño de un negocio grande, tiene un cargo ...",Es vendedor o trabaja en atención al público,Si,Si,Si,Si,Si,Si,No,Si,0 A 10 LIBROS,Todos o casi todos los días,Todos o casi todos los días,Todos o casi todos los días,Mejor,30 minutos o menos,Más de 3 horas,0,No,MIXTO,NO OFICIAL,A,N,ACADÉMICO,S,URBANO,COMPLETA,BOGOTÁ D.C.,BOGOTÁ,63,54,67,59,76.0,310,67.171655,4.0,3.0
2519,NES,VENEZUELA,F,2007,No,Estrato 1,3 a 4,Dos,Primaria completa,Secundaria (Bachillerato) completa,Trabaja por cuenta propia (por ejemplo plomero...,"Trabaja en el hogar, no trabaja o estudia",Si,Si,No,Si,No,No,No,No,0 A 10 LIBROS,3 a 5 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Igual,Entre 30 y 60 minutos,Entre 1 y 3 horas,0,No,MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,UNICA,CALI,VALLE,50,63,52,61,54.0,282,47.663285,2.0,2.0
3095,TI,COLOMBIA,F,2020,No,Estrato 1,5 a 6,Cuatro,Primaria incompleta,Primaria incompleta,"Trabaja en el hogar, no trabaja o estudia","Trabaja en el hogar, no trabaja o estudia",No,No,No,No,No,No,Si,No,0 A 10 LIBROS,1 o 2 veces por semana,1 o 2 veces por semana,Nunca o rara vez comemos eso,Igual,30 minutos o menos,Entre 30 y 60 minutos,Menos de 10 horas,No,MIXTO,OFICIAL,A,N,TÉCNICO,S,URBANO,NOCHE,RIOSUCIO,CALDAS,48,33,35,41,43.0,198,33.096566,1.0,2.0
3315,CE,VENEZUELA,F,2008,No,Estrato 2,3 a 4,Dos,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) incompleta,Es vendedor o trabaja en atención al público,Es dueño de un negocio pequeño (tiene pocos em...,Si,Si,No,Si,No,No,No,No,0 A 10 LIBROS,1 o 2 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Peor,30 minutos o menos,No Navega Internet,0,No,MIXTO,NO OFICIAL,A,N,ACADÉMICO,S,URBANO,TARDE,SOLEDAD,ATLANTICO,46,50,49,45,37.0,233,48.115187,2.0,2.0
3651,NES,VENEZUELA,M,2013,No,Estrato 2,3 a 4,Dos,Primaria incompleta,Postgrado,"Trabaja como personal de limpieza, mantenimien...",Trabaja por cuenta propia (por ejemplo plomero...,Si,No,Si,No,Si,No,No,No,0 A 10 LIBROS,3 a 5 veces por semana,3 a 5 veces por semana,3 a 5 veces por semana,Igual,Entre 1 y 2 horas,Entre 1 y 3 horas,0,No,MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,MAÑANA,BOGOTÁ D.C.,BOGOTÁ,49,50,51,52,47.0,251,49.384147,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489965,TI,COLOMBIA,F,2014,No,Estrato 2,3 a 4,Dos,Secundaria (Bachillerato) completa,Educación profesional completa,"Trabaja como personal de limpieza, mantenimien...","Trabaja como profesional (por ejemplo médico, ...",Si,Si,No,No,No,No,No,No,0 A 10 LIBROS,Nunca o rara vez comemos eso,Todos o casi todos los días,1 o 2 veces por semana,Peor,No leo por entretenimiento,Más de 3 horas,Menos de 10 horas,No,MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,TARDE,BOGOTÁ D.C.,BOGOTÁ,39,55,43,40,40.0,220,47.489521,2.0,3.0
498029,TI,COLOMBIA,F,2013,No,Estrato 3,5 a 6,Seis o mas,Primaria completa,Secundaria (Bachillerato) completa,Es operario de máquinas o conduce vehículos (t...,"Trabaja en el hogar, no trabaja o estudia",Si,Si,Si,Si,Si,No,No,No,26 A 100 LIBROS,Todos o casi todos los días,Todos o casi todos los días,Todos o casi todos los días,Igual,30 minutos o menos,Entre 30 y 60 minutos,0,No,MIXTO,NO OFICIAL,A,N,ACADÉMICO,S,URBANO,COMPLETA,BOGOTÁ D.C.,BOGOTÁ,62,62,56,66,43.0,300,55.841628,3.0,3.0
499178,CC,COLOMBIA,M,2010,No,Estrato 2,5 a 6,Tres,No sabe,Secundaria (Bachillerato) completa,No sabe,Es dueño de un negocio pequeño (tiene pocos em...,Si,Si,No,No,No,No,No,Si,0 A 10 LIBROS,Nunca o rara vez comemos eso,3 a 5 veces por semana,Nunca o rara vez comemos eso,Peor,No leo por entretenimiento,Más de 3 horas,0,No,MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,NOCHE,BELLO,ANTIOQUIA,45,41,38,41,47.0,208,46.705701,2.0,3.0
503419,TI,COLOMBIA,F,2008,No,Estrato 3,3 a 4,Cuatro,Técnica o tecnológica completa,Educación profesional incompleta,Es dueño de un negocio pequeño (tiene pocos em...,"Trabaja en el hogar, no trabaja o estudia",Si,Si,Si,Si,Si,Si,Si,Si,11 A 25 LIBROS,Todos o casi todos los días,3 a 5 veces por semana,3 a 5 veces por semana,Peor,30 minutos o menos,Más de 3 horas,0,No,MIXTO,NO OFICIAL,A,None,ACADÉMICO,S,URBANO,COMPLETA,BOGOTÁ D.C.,BOGOTÁ,67,68,52,61,70.0,313,63.474890,3.0,3.0
504395,TI,COLOMBIA,M,2013,No,Estrato 2,3 a 4,Tres,No sabe,Técnica o tecnológica completa,No sabe,No sabe,Si,Si,Si,Si,Si,No,Si,No,0 A 10 LIBROS,3 a 5 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Igual,No leo por entretenimiento,Más de 3 horas,0,No,MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,UNICA,MEDELLÍN,ANTIOQUIA,47,42,38,25,43.0,192,55.178269,3.0,3.0

In [14]:
import numpy as np

def corregir_anio_nacimiento(row):
    anio = row['anio_nacimiento']
    
    # Si es NaN o valor absurdo
    if pd.isna(anio):
        return np.nan
    
    anio = int(anio)
    
    # Caso 1: años 1, 2, 3, 4 → claramente son 2001, 2002, 2003, 2004
    if 1 <= anio <= 9:
        return 2000 + anio
    
    # Caso 2: año 2020 y tiene cédula → imposible para un menor → es el año del examen
    if anio == 2020 and row['tipo_documento'] == 'CC':
        # estimamos edad típica con cédula: 18–25 años → nació entre 1995–2002
        return np.random.randint(1995, 2003)
    
    # Caso 3: año 2020 pero es TI (tarjeta identidad) → sí puede ser menor de edad
    # → probablemente nació entre 2001–2004
    if anio == 2020 and row['tipo_documento'] == 'TI':
        return np.random.randint(2001, 2005)
    
    # Caso 4: años 1900–1930 → valor por defecto → imputamos por mediana del estrato o colegio
    if 1900 <= anio <= 1930:
        return np.nan  # lo dejaremos para imputar después por grupo
    
    # Caso 5: años imposibles (< 1950 o > 2010) → marcamos como NaN
    if anio < 1950 or anio > 2010:
        return np.nan
    
    # Si no cae en ningún caso raro → lo dejamos como está
    return anio

# Aplicar la función
icfes['anio_nacimiento_corregido'] = icfes.apply(corregir_anio_nacimiento, axis=1)

In [15]:
icfes['anio_nacimiento_corregido'].value_counts().sort_index()

anio_nacimiento_corregido
1950.0      3
1951.0      7
1952.0      6
1953.0     15
1954.0     10
         ...
2006.0    159
2007.0     31
2008.0     24
2009.0     25
2010.0     29
Name: count, Length: 61, dtype: int64

In [16]:
icfes['edad'] = 2020 - icfes['anio_nacimiento_corregido'].astype('float')
icfes['edad'].value_counts()

edad
17.0    214717
16.0    111089
18.0    102683
19.0     41797
20.0     12451
         ...
66.0        10
69.0         7
65.0         7
68.0         6
70.0         3
Name: count, Length: 61, dtype: int64

In [17]:
icfes = icfes.drop(columns=['anio_nacimiento', 'anio_nacimiento_corregido'],
                   errors='ignore')
icfes.sample(6)

,tipo_documento,nacionalidad,genero,pertenece_etnia,estrato_casa,num_personas_casa,cuartos_casa,educacion_padre,educacion_madre,actividad_padre,actividad_madre,internet,tv,computador,lavadora,microndas,carro,moto,consola,num_libros_casa,come_derivados_leche,come_carne_pescado_huevo,come_cereal_frutas_legumbres,situacion_economica,cuanto_lee,cuanto_navega_web,horas_trabajo_semanal,tipo_pago_trabajo,colegio_genero,colegio_oficial,colegio_calendario,colegio_bilingue,tipo_colegio,colegio_sede_principal,colegio_urbano_rural,colegio_jornada,mpio_colegio,dpto_colegio,puntaje_lectura,puntaje_matematicas,puntaje_naturales,puntaje_sociales,puntaje_ingles,puntaje_global,inse_estudiante,nse_estudiantes,nse_colegio,edad
228764,TI,COLOMBIA,F,No,Estrato 1,3 a 4,Dos,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) completa,Es dueño de un negocio pequeño (tiene pocos em...,"Trabaja en el hogar, no trabaja o estudia",Si,No,No,No,No,No,Si,No,11 A 25 LIBROS,1 o 2 veces por semana,1 o 2 veces por semana,3 a 5 veces por semana,Peor,Entre 1 y 2 horas,Entre 30 y 60 minutos,Menos de 10 horas,"Si, en efectivo",MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,TARDE,PEREIRA,RISARALDA,60,58,55,67,54.0,298,44.587536,2.0,3.0,17.0
4731,CC,COLOMBIA,F,No,Estrato 3,3 a 4,Tres,Primaria incompleta,Primaria incompleta,No sabe,"Trabaja en el hogar, no trabaja o estudia",Si,Si,Si,Si,No,No,No,No,0 A 10 LIBROS,1 o 2 veces por semana,Todos o casi todos los días,Todos o casi todos los días,Igual,30 minutos o menos,Más de 3 horas,Menos de 10 horas,No,MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,NOCHE,PEREIRA,RISARALDA,39,27,37,30,34.0,167,47.223874,2.0,2.0,20.0
288876,TI,COLOMBIA,F,No,Estrato 3,3 a 4,Tres,Primaria completa,Secundaria (Bachillerato) completa,Es operario de máquinas o conduce vehículos (t...,"Trabaja en el hogar, no trabaja o estudia",Si,Si,Si,Si,Si,Si,No,No,26 A 100 LIBROS,Todos o casi todos los días,Todos o casi todos los días,Todos o casi todos los días,Igual,Entre 30 y 60 minutos,Más de 3 horas,0,No,MIXTO,NO OFICIAL,A,N,ACADÉMICO,S,URBANO,MAÑANA,CHOCONTÁ,CUNDINAMARCA,61,65,52,58,60.0,295,57.943237,3.0,3.0,17.0
248097,TI,COLOMBIA,F,No,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,COMPLETA,MARINILLA,ANTIOQUIA,40,34,42,33,47.0,190,NaN,NaN,3.0,17.0
236760,TI,COLOMBIA,F,No,Estrato 3,5 a 6,Dos,Secundaria (Bachillerato) completa,None,Tiene un trabajo de tipo auxiliar administrati...,Es dueño de un negocio pequeño (tiene pocos em...,Si,Si,No,No,No,No,Si,No,0 A 10 LIBROS,3 a 5 veces por semana,1 o 2 veces por semana,3 a 5 veces por semana,Igual,30 minutos o menos,Entre 30 y 60 minutos,0,No,MIXTO,OFICIAL,A,N,ACADÉMICO,S,URBANO,MAÑANA,BOGOTÁ D.C.,BOGOTÁ,54,53,33,40,39.0,223,47.597093,2.0,3.0,18.0
181678,TI,COLOMBIA,M,No,Estrato 2,3 a 4,Tres,Técnica o tecnológica incompleta,Secundaria (Bachillerato) completa,"Es dueño de un negocio grande, tiene un cargo ...","Trabaja en el hogar, no trabaja o estudia",Si,Si,Si,Si,Si,Si,No,Si,0 A 10 LIBROS,Nunca o rara vez comemos eso,Todos o casi todos los días,Nunca o rara vez comemos eso,Mejor,Entre 30 y 60 minutos,Entre 30 y 60 minutos,0,No,MIXTO,NO OFICIAL,A,N,ACADÉMICO,S,URBANO,COMPLETA,BOGOTÁ D.C.,BOGOTÁ,39,52,46,41,38.0,220,58.768154,3.0,3.0,17.0

### 4. Estandarizar categorías de variables

In [18]:
icfes.sample(5)

,tipo_documento,nacionalidad,genero,pertenece_etnia,estrato_casa,num_personas_casa,cuartos_casa,educacion_padre,educacion_madre,actividad_padre,actividad_madre,internet,tv,computador,lavadora,microndas,carro,moto,consola,num_libros_casa,come_derivados_leche,come_carne_pescado_huevo,come_cereal_frutas_legumbres,situacion_economica,cuanto_lee,cuanto_navega_web,horas_trabajo_semanal,tipo_pago_trabajo,colegio_genero,colegio_oficial,colegio_calendario,colegio_bilingue,tipo_colegio,colegio_sede_principal,colegio_urbano_rural,colegio_jornada,mpio_colegio,dpto_colegio,puntaje_lectura,puntaje_matematicas,puntaje_naturales,puntaje_sociales,puntaje_ingles,puntaje_global,inse_estudiante,nse_estudiantes,nse_colegio,edad
130749,TI,COLOMBIA,F,No,Estrato 3,3 a 4,Tres,Educación profesional completa,Educación profesional completa,Pensionado,"Trabaja como profesional (por ejemplo médico, ...",Si,Si,Si,Si,Si,Si,Si,No,11 A 25 LIBROS,3 a 5 veces por semana,Todos o casi todos los días,1 o 2 veces por semana,Peor,Entre 30 y 60 minutos,Entre 1 y 3 horas,0,No,MIXTO,NO OFICIAL,A,N,ACADÉMICO,S,RURAL,COMPLETA,YOPAL,CASANARE,59,57,56,60,54.0,288,66.398751,4.0,4.0,16.0
424771,TI,COLOMBIA,M,No,Estrato 1,5 a 6,Dos,Primaria completa,Primaria completa,"Trabaja en el hogar, no trabaja o estudia","Trabaja en el hogar, no trabaja o estudia",No,No,No,No,No,No,No,No,0 A 10 LIBROS,3 a 5 veces por semana,Nunca o rara vez comemos eso,Todos o casi todos los días,Mejor,30 minutos o menos,No Navega Internet,0,No,MIXTO,OFICIAL,A,None,ACADÉMICO,S,RURAL,COMPLETA,SOGAMOSO,BOYACA,46,58,41,54,41.0,245,37.583502,1.0,2.0,18.0
179437,TI,COLOMBIA,F,No,Estrato 3,3 a 4,Tres,Educación profesional completa,Secundaria (Bachillerato) completa,Es vendedor o trabaja en atención al público,Es vendedor o trabaja en atención al público,Si,Si,Si,Si,No,Si,Si,No,0 A 10 LIBROS,Todos o casi todos los días,Todos o casi todos los días,3 a 5 veces por semana,Peor,No leo por entretenimiento,Entre 1 y 3 horas,0,No,MIXTO,NO OFICIAL,A,None,ACADÉMICO,S,URBANO,COMPLETA,RIONEGRO,ANTIOQUIA,59,45,55,34,57.0,245,59.213338,3.0,3.0,17.0
411179,TI,COLOMBIA,F,No,Estrato 3,3 a 4,Tres,No sabe,No sabe,No sabe,"Trabaja en el hogar, no trabaja o estudia",Si,Si,Si,Si,Si,No,Si,No,0 A 10 LIBROS,3 a 5 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Peor,Entre 30 y 60 minutos,Entre 1 y 3 horas,0,No,MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,RURAL,UNICA,MEDELLÍN,ANTIOQUIA,72,61,56,63,59.0,313,52.813421,3.0,3.0,16.0
462180,TI,COLOMBIA,F,No,Estrato 2,1 a 2,Dos,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,Es vendedor o trabaja en atención al público,Es dueño de un negocio pequeño (tiene pocos em...,Si,Si,No,No,Si,No,No,No,0 A 10 LIBROS,1 o 2 veces por semana,1 o 2 veces por semana,1 o 2 veces por semana,Igual,No leo por entretenimiento,Entre 30 y 60 minutos,0,No,MIXTO,OFICIAL,A,N,TÉCNICO/ACADÉMICO,S,URBANO,UNICA,MEDELLÍN,ANTIOQUIA,53,55,54,46,39.0,255,49.016709,2.0,2.0,17.0

In [19]:
vars_cat = ['tipo_documento', 'nacionalidad', 'genero', 'pertenece_etnia', 'estrato_casa', 'educacion_padre', 'educacion_madre',
            'actividad_padre', 'actividad_madre', 'internet', 'tv', 'computador', 'lavadora', 'microndas', 'carro','moto', 'consola',
            'num_libros_casa', 'come_derivados_leche', 'come_carne_pescado_huevo', 'come_cereal_frutas_legumbres', 'situacion_economica',
            'cuanto_lee', 'cuanto_navega_web', 'horas_trabajo_semanal', 'tipo_pago_trabajo', 'colegio_genero', 'colegio_oficial',
            'colegio_calendario', 'colegio_bilingue', 'tipo_colegio', 'colegio_sede_principal', 'colegio_urbano_rural', 'colegio_jornada',
            'mpio_colegio', 'dpto_colegio']

icfes[vars_cat] = icfes[vars_cat].astype('category')

In [20]:
variables_estandarizar = ['nacionalidad', 'pertenece_etnia', 'estrato_casa', 'educacion_padre', 'educacion_madre',
            'actividad_padre', 'actividad_madre', 'internet', 'tv', 'computador', 'lavadora', 'microndas', 'carro',
            'moto', 'consola', 'num_libros_casa', 'come_derivados_leche', 'come_carne_pescado_huevo', 'come_cereal_frutas_legumbres', 
            'situacion_economica', 'cuanto_lee', 'cuanto_navega_web', 'horas_trabajo_semanal', 'tipo_pago_trabajo', 'colegio_genero', 
            'colegio_oficial', 'colegio_calendario', 'colegio_bilingue', 'tipo_colegio', 'colegio_sede_principal', 'colegio_urbano_rural', 
            'colegio_jornada', 'mpio_colegio', 'dpto_colegio']

icfes[variables_estandarizar] = icfes[variables_estandarizar].apply(lambda x: x.str.capitalize() if x.dtype == "category" else x)
icfes.sample(8)

,tipo_documento,nacionalidad,genero,pertenece_etnia,estrato_casa,num_personas_casa,cuartos_casa,educacion_padre,educacion_madre,actividad_padre,actividad_madre,internet,tv,computador,lavadora,microndas,carro,moto,consola,num_libros_casa,come_derivados_leche,come_carne_pescado_huevo,come_cereal_frutas_legumbres,situacion_economica,cuanto_lee,cuanto_navega_web,horas_trabajo_semanal,tipo_pago_trabajo,colegio_genero,colegio_oficial,colegio_calendario,colegio_bilingue,tipo_colegio,colegio_sede_principal,colegio_urbano_rural,colegio_jornada,mpio_colegio,dpto_colegio,puntaje_lectura,puntaje_matematicas,puntaje_naturales,puntaje_sociales,puntaje_ingles,puntaje_global,inse_estudiante,nse_estudiantes,nse_colegio,edad
284349,TI,Colombia,M,No,Estrato 2,3 a 4,Tres,Primaria incompleta,Educación profesional incompleta,Es dueño de un negocio pequeño (tiene pocos em...,Es dueño de un negocio pequeño (tiene pocos em...,Si,Si,Si,Si,Si,No,Si,No,11 a 25 libros,3 a 5 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Mejor,Entre 30 y 60 minutos,Más de 3 horas,0,"Si, en efectivo",Mixto,Oficial,A,N,Académico,S,Urbano,Mañana,Cúcuta,Norte santander,76,65,64,69,64.0,341,55.827657,3.0,3.0,17.0
222762,TI,Colombia,F,No,Estrato 2,5 a 6,Dos,Ninguno,Ninguno,"Trabaja en el hogar, no trabaja o estudia",Es dueño de un negocio pequeño (tiene pocos em...,No,Si,No,No,No,No,No,No,0 a 10 libros,1 o 2 veces por semana,Nunca o rara vez comemos eso,Nunca o rara vez comemos eso,Igual,Entre 1 y 2 horas,30 minutos o menos,Menos de 10 horas,"Si, en efectivo",Mixto,Oficial,A,N,Técnico,S,Urbano,Completa,Chiquinquirá,Boyaca,58,60,35,66,40.0,268,29.001384,1.0,2.0,17.0
435413,TI,Colombia,M,No,Estrato 3,5 a 6,Cuatro,Secundaria (bachillerato) completa,Secundaria (bachillerato) completa,"Trabaja en el hogar, no trabaja o estudia","Trabaja en el hogar, no trabaja o estudia",No,No,Si,Si,Si,No,Si,Si,0 a 10 libros,Todos o casi todos los días,Todos o casi todos los días,3 a 5 veces por semana,Mejor,Entre 1 y 2 horas,Entre 30 y 60 minutos,Menos de 10 horas,"Si, en efectivo",Mixto,Oficial,A,N,Académico,S,Rural,Mañana,Montería,Cordoba,34,34,33,28,38.0,163,50.718838,2.0,2.0,20.0
117245,TI,Colombia,F,No,Estrato 4,3 a 4,Tres,Educación profesional completa,Postgrado,"Trabaja como profesional (por ejemplo médico, ...","Trabaja como profesional (por ejemplo médico, ...",Si,Si,Si,Si,No,Si,No,No,Más de 100 libros,3 a 5 veces por semana,Todos o casi todos los días,1 o 2 veces por semana,Peor,Entre 1 y 2 horas,30 minutos o menos,0,No,Mixto,No oficial,A,N,Académico,S,Urbano,Completa,Duitama,Boyaca,76,80,68,77,78.0,377,69.452252,4.0,4.0,16.0
151156,TI,Colombia,F,No,Estrato 3,3 a 4,Tres,Técnica o tecnológica completa,Técnica o tecnológica completa,Es dueño de un negocio pequeño (tiene pocos em...,Tiene un trabajo de tipo auxiliar administrati...,Si,Si,Si,Si,Si,No,No,No,26 a 100 libros,1 o 2 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Peor,30 minutos o menos,Entre 1 y 3 horas,0,No,Mixto,Oficial,A,N,Académico,S,Urbano,Mañana,Bogotá d.c.,Bogotá,52,41,38,40,41.0,213,58.478524,3.0,3.0,18.0
10556,TI,Colombia,M,No,Estrato 4,3 a 4,Tres,Técnica o tecnológica completa,Técnica o tecnológica completa,Es dueño de un negocio pequeño (tiene pocos em...,NaN,Si,Si,Si,Si,No,Si,Si,No,26 a 100 libros,1 o 2 veces por semana,1 o 2 veces por semana,NaN,Igual,Entre 1 y 2 horas,Entre 1 y 3 horas,Entre 11 y 20 horas,No,Mixto,Oficial,A,N,Técnico/académico,S,Urbano,Completa,Fundación,Magdalena,48,44,44,39,31.0,214,57.262700,3.0,2.0,17.0
116889,TI,Colombia,M,No,Estrato 2,3 a 4,Dos,Secundaria (bachillerato) completa,Secundaria (bachillerato) completa,Es vendedor o trabaja en atención al público,Es vendedor o trabaja en atención al público,Si,Si,Si,Si,Si,No,No,No,0 a 10 libros,1 o 2 veces por semana,1 o 2 veces por semana,Nunca o rara vez comemos eso,Igual,Entre 30 y 60 minutos,Entre 30 y 60 minutos,Menos de 10 horas,"Si, en efectivo",Mixto,Oficial,A,S,Técnico/académico,S,Urbano,Unica,Espinal,Tolima,49,38,57,56,54.0,252,51.440710,3.0,2.0,16.0
375172,TI,Colombia,M,No,Estrato 2,3 a 4,Tres,Técnica o tecnológica incompleta,Educación profesional completa,Trabaja por cuenta propia (por ejemplo plomero...,"Trabaja como profesional (por ejemplo médico, ...",Si,Si,Si,Si,No,No,No,Si,Más de 100 libros,1 o 2 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Mejor,Entre 30 y 60 minutos,Más de 3 horas,0,"Si, en efectivo",Mixto,No oficial,A,N,Académico,S,Urbano,Completa,Bogotá d.c.,Bogotá,60,59,55,55,66.0,290,58.875409,3.0,3.0,16.0

#### 4.1 Homogenización de categorías

In [21]:
icfes['genero'].value_counts(dropna=False)

genero
F      276572
M      228290
NaN         8
Name: count, dtype: int64

In [22]:
icfes['genero'] = icfes['genero'].map({'F': 'Femenino', 'M': 'Masculino'}).fillna('Masculino')

icfes['genero'].value_counts(dropna=False)

genero
Femenino     276572
Masculino    228298
Name: count, dtype: int64

In [23]:
icfes['colegio_bilingue'].value_counts(dropna=False)

colegio_bilingue
N      416665
NaN     83006
S        5199
Name: count, dtype: int64

In [24]:
icfes['colegio_bilingue'] = icfes['colegio_bilingue'].map({'N': 'No', 'S': 'Si'}).fillna('No')
icfes['colegio_bilingue'].value_counts(dropna=False)

colegio_bilingue
No    499671
Si      5199
Name: count, dtype: int64

In [25]:
icfes['colegio_sede_principal'].value_counts(dropna=False)

colegio_sede_principal
S    480831
N     24039
Name: count, dtype: int64

In [26]:
icfes['colegio_sede_principal'] = icfes['colegio_sede_principal'].map({'N': 'No', 'S': 'Si'})
icfes['colegio_sede_principal'].value_counts(dropna=False)

colegio_sede_principal
Si    480831
No     24039
Name: count, dtype: int64

#### 4.2 Recodificación Semántica

In [27]:
icfes.sample(8)

,tipo_documento,nacionalidad,genero,pertenece_etnia,estrato_casa,num_personas_casa,cuartos_casa,educacion_padre,educacion_madre,actividad_padre,actividad_madre,internet,tv,computador,lavadora,microndas,carro,moto,consola,num_libros_casa,come_derivados_leche,come_carne_pescado_huevo,come_cereal_frutas_legumbres,situacion_economica,cuanto_lee,cuanto_navega_web,horas_trabajo_semanal,tipo_pago_trabajo,colegio_genero,colegio_oficial,colegio_calendario,colegio_bilingue,tipo_colegio,colegio_sede_principal,colegio_urbano_rural,colegio_jornada,mpio_colegio,dpto_colegio,puntaje_lectura,puntaje_matematicas,puntaje_naturales,puntaje_sociales,puntaje_ingles,puntaje_global,inse_estudiante,nse_estudiantes,nse_colegio,edad
55731,TI,Colombia,Masculino,No,Estrato 3,5 a 6,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Trabaja por cuenta propia (por ejemplo plomero...,Es operario de máquinas o conduce vehículos (t...,Si,No,No,Si,No,No,Si,No,26 a 100 libros,1 o 2 veces por semana,1 o 2 veces por semana,3 a 5 veces por semana,Igual,30 minutos o menos,Entre 1 y 3 horas,0,No,Mixto,Oficial,A,No,Técnico,Si,Urbano,Unica,Santa rosa de cabal,Risaralda,44,55,51,48,36.0,242,49.395616,2.0,3.0,16.0
175829,TI,Colombia,Femenino,No,Estrato 1,3 a 4,Dos,No sabe,Secundaria (bachillerato) incompleta,No sabe,"Trabaja en el hogar, no trabaja o estudia",Si,Si,Si,Si,No,No,No,No,11 a 25 libros,Nunca o rara vez comemos eso,1 o 2 veces por semana,Nunca o rara vez comemos eso,Igual,Entre 30 y 60 minutos,Entre 1 y 3 horas,0,No,Mixto,Oficial,A,No,Técnico/académico,Si,Urbano,Mañana,Villavicencio,Meta,44,44,41,34,44.0,205,47.513149,2.0,2.0,17.0
18394,TI,Colombia,Femenino,No,Estrato 2,3 a 4,Dos,Secundaria (bachillerato) incompleta,Primaria completa,"Trabaja como personal de limpieza, mantenimien...",Es vendedor o trabaja en atención al público,Si,Si,Si,Si,Si,No,No,No,11 a 25 libros,Nunca o rara vez comemos eso,1 o 2 veces por semana,3 a 5 veces por semana,Peor,Entre 30 y 60 minutos,Más de 3 horas,Entre 11 y 20 horas,"Si, en efectivo",Mixto,Oficial,A,No,Académico,Si,Urbano,Mañana,Bogotá d.c.,Bogotá,57,59,54,59,35.0,278,48.429294,2.0,3.0,17.0
374234,TI,Colombia,Femenino,No,Estrato 2,5 a 6,Dos,No sabe,Secundaria (bachillerato) completa,No sabe,No sabe,No,Si,No,No,No,No,No,No,11 a 25 libros,Nunca o rara vez comemos eso,1 o 2 veces por semana,1 o 2 veces por semana,Igual,No leo por entretenimiento,Entre 1 y 3 horas,0,No,Mixto,Oficial,A,Si,Técnico/académico,Si,Urbano,Mañana,Jamundí,Valle,40,41,35,28,36.0,180,38.407382,1.0,2.0,17.0
273517,CC,Colombia,Femenino,No,Estrato 2,7 a 8,Uno,Ninguno,Ninguno,"Es dueño de un negocio grande, tiene un cargo ...","Es dueño de un negocio grande, tiene un cargo ...",Si,Si,Si,Si,Si,No,No,No,0 a 10 libros,Nunca o rara vez comemos eso,1 o 2 veces por semana,NaN,Peor,NaN,NaN,0,No,Mixto,Oficial,A,No,Académico,Si,Urbano,Noche,Cartagena de indias,Bolivar,38,32,35,34,33.0,173,47.513498,2.0,2.0,25.0
308353,CC,Colombia,Femenino,Si,Estrato 1,5 a 6,Cuatro,Primaria completa,Primaria incompleta,NaN,"Es dueño de un negocio grande, tiene un cargo ...",No,Si,No,Si,No,No,No,No,0 a 10 libros,Nunca o rara vez comemos eso,Todos o casi todos los días,1 o 2 veces por semana,Peor,30 minutos o menos,Entre 1 y 3 horas,0,No,Mixto,Oficial,A,No,Académico,Si,Rural,Unica,Moñitos,Cordoba,62,58,43,54,47.0,268,41.833669,2.0,2.0,18.0
150297,TI,Colombia,Femenino,No,Estrato 2,5 a 6,Tres,Secundaria (bachillerato) completa,Secundaria (bachillerato) incompleta,Es dueño de un negocio pequeño (tiene pocos em...,"Trabaja en el hogar, no trabaja o estudia",Si,Si,No,Si,No,No,Si,No,0 a 10 libros,1 o 2 veces por semana,3 a 5 veces por semana,Todos o casi todos los días,Peor,Entre 30 y 60 minutos,30 minutos o menos,0,No,Mixto,Oficial,A,No,Técnico/académico,Si,Urbano,Tarde,Santa marta,Magdalena,72,56,69,68,57.0,328,49.042350,2.0,3.0,17.0
96414,TI,Colombia,Masculino,No,Estrato 2,9 o más,Seis o mas,Secundaria (bachillerato) incompleta,Técnica o tecnológica completa,"Es agricultor, pesquero o jornalero","Trabaja en el hogar, no trabaja o estudia",No,Si,Si,Si,No,Si,Si,No,26 a 100 libros,1 o 2 veces por semana,3 a 5 veces por semana,1 o 2 veces por semana,Mejor,Entre 30 y 60 minutos,No navega internet,Entre 11 y 20 horas,"Si, en efectivo",Mixto,Oficial,A,No,Técnico/académico,Si,Urbano,Unica,Apía,Risaralda,38,33,40,38,36.0,186,48.154931,2.0,2.0,16.0

In [28]:
icfes['actividad_madre'].value_counts(dropna=False)

actividad_madre
Trabaja en el hogar, no trabaja o estudia                                                               188123
Es dueño de un negocio pequeño (tiene pocos empleados o no tiene, por ejemplo tienda, papelería, etc     73718
Trabaja como personal de limpieza, mantenimiento, seguridad o construcción                               40669
Trabaja como profesional (por ejemplo médico, abogado, ingeniero)                                        40346
Es vendedor o trabaja en atención al público                                                             38526
Tiene un trabajo de tipo auxiliar administrativo (por ejemplo, secretario o asistente)                   38235
NaN                                                                                                      17598
Trabaja por cuenta propia (por ejemplo plomero, electricista)                                            17388
Es agricultor, pesquero o jornalero                                                                      15991
No sabe                                                                                                  13383
Es dueño de un negocio grande, tiene un cargo de nivel directivo o gerencial                              9516
Es operario de máquinas o conduce vehículos (taxita, chofer)                                              7754
Pensionado                                                                                                3623
Name: count, dtype: int64

In [29]:
# Definir el mapeo de categorías
mapeo_actividad = {
    # Profesionales y Directivos
    'Es dueño de un negocio grande, tiene un cargo de nivel directivo o gerencial': 'Directivos',
    'Trabaja como profesional (por ejemplo médico, abogado, ingeniero)': 'Profesionales',

    # Trabajadores Independientes y Pequeños Empresarios
    'Es dueño de un negocio pequeño (tiene pocos empleados o no tiene, por ejemplo tienda, papelería, etc': 'Microempresario',
    'Trabaja por cuenta propia (por ejemplo plomero, electricista)': 'Trabajador independiente',

    # Trabajadores Operativos y de Servicios
    'Es operario de máquinas o conduce vehículos (taxita, chofer)': 'Trabajadores operativos',
    'Es vendedor o trabaja en atención al público': 'Trabajadores operativos',
    'Tiene un trabajo de tipo auxiliar administrativo (por ejemplo, secretario o asistente)': 'Trabajadores operativos',
    'Trabaja como personal de limpieza, mantenimiento, seguridad o construcción': 'Trabajadores operativos',
    
    # Trabajadores del Sector Primario
    'Es agricultor, pesquero o jornalero': 'Sector primario',
    
    # Sin Actividad Laboral Remunerada
    'Trabaja en el hogar, no trabaja o estudia': 'Sin actividad remunerada',
    'Pensionado': 'Pensionado',
    
    # Datos No Disponibles
    'No aplica': 'No aplica',
    'No sabe': 'Sin informacion'
}

# Aplicar la reclasificación directamente a cada columna
icfes['actividad_madre'] = icfes['actividad_madre'].map(mapeo_actividad)
icfes['actividad_padre'] = icfes['actividad_padre'].map(mapeo_actividad)

In [30]:
icfes['actividad_madre'].value_counts(dropna=False)

actividad_madre
Sin actividad remunerada    188123
Trabajadores operativos     125184
Microempresario              73718
Profesionales                40346
NaN                          17598
Trabajador independiente     17388
Sector primario              15991
Sin informacion              13383
Directivos                    9516
Pensionado                    3623
Name: count, dtype: int64

In [31]:
icfes['educacion_madre'].value_counts(dropna=False)

educacion_madre
Secundaria (bachillerato) completa      137647
Primaria incompleta                      71289
Secundaria (bachillerato) incompleta     68181
Educación profesional completa           56344
Técnica o tecnológica completa           50487
Primaria completa                        45987
Técnica o tecnológica incompleta         15198
NaN                                      13485
Educación profesional incompleta         12621
Ninguno                                  12363
Postgrado                                11239
No sabe                                   8859
No aplica                                 1170
Name: count, dtype: int64

In [32]:
mapeo_educacion = {
    #Educación Incompleta
    'Primaria incompleta': 'Primaria incompleta',
    'Secundaria (Bachillerato) incompleta': 'Bachiller incompleta',
    'Técnica o tecnológica incompleta': 'Tecnico/Tecnologo incompleta',
    'Educación profesional incompleta': 'Profesional incompleta',

    #Educación Completa
    'Primaria completa': 'Primaria',
    'Secundaria (Bachillerato) completa': 'Bachiller',
    'Técnica o tecnológica completa': 'Tecnico/Tecnologo',
    'Educación profesional completa': 'Profesional',
    
    #Otros
    'Ninguno': 'Ninguna',
    'No aplica': 'No aplica',
    'No sabe': np.nan,
}

# Aplicar la reclasificación directamente a cada columna
icfes['educacion_madre'] = icfes['educacion_madre'].map(mapeo_educacion)
icfes['educacion_padre'] = icfes['educacion_padre'].map(mapeo_educacion)

In [33]:
icfes['educacion_madre'].value_counts(dropna=False).sort_index()

educacion_madre
Ninguna                          12363
No aplica                         1170
Primaria                         45987
Primaria incompleta              71289
Profesional                      56344
Profesional incompleta           12621
Tecnico/Tecnologo                50487
Tecnico/Tecnologo incompleta     15198
NaN                             239411
Name: count, dtype: int64

In [34]:
icfes['educacion_padre'].value_counts(dropna=False).sort_index()

educacion_padre
Ninguna                          20798
No aplica                         7735
Primaria                         45931
Primaria incompleta              92089
Profesional                      46737
Profesional incompleta           10231
Tecnico/Tecnologo                33073
Tecnico/Tecnologo incompleta     10221
NaN                             238055
Name: count, dtype: int64

In [35]:
icfes["horas_trabajo_semanal"].value_counts()

horas_trabajo_semanal
0                      293827
Menos de 10 horas       95286
Entre 11 y 20 horas     51044
Más de 30 horas         26121
Entre 21 y 30 horas     21609
Name: count, dtype: int64

In [36]:
icfes["horas_trabajo_semanal"] = icfes["horas_trabajo_semanal"].replace({'0': 'No trabaja',
        'Menos de 10 horas': 'Trabajo ocasional',
        'Entre 11 y 20 horas': 'Tiempo parcial reducido',
        'Entre 21 y 30 horas': 'Medio tiempo',
        'Más de 30 horas': 'Tiempo completo'
})

icfes["horas_trabajo_semanal"].value_counts()

horas_trabajo_semanal
No trabaja                 293827
Trabajo ocasional           95286
Tiempo parcial reducido     51044
Tiempo completo             26121
Medio tiempo                21609
Name: count, dtype: int64

In [37]:
icfes['tipo_pago_trabajo'].value_counts(dropna=False)

tipo_pago_trabajo
No                           324731
Si, en efectivo              141637
NaN                           17645
Si, en especie                11384
Si, en efectivo y especie      9473
Name: count, dtype: int64

In [38]:
icfes["tipo_pago_trabajo"] = icfes["tipo_pago_trabajo"].replace({'No': 'Sin pago',
        'Si, en efectivo': 'Remuneración monetaria',
        'Si, en especie': 'Remuneración no monetaria',
        'Si, en efectivo y especie': 'Remuneración mixta'})

icfes["tipo_pago_trabajo"].value_counts()

tipo_pago_trabajo
Sin pago                     324731
Remuneración monetaria       141637
Remuneración no monetaria     11384
Remuneración mixta             9473
Name: count, dtype: int64

In [39]:
icfes.loc[icfes["horas_trabajo_semanal"] == "No trabaja", "tipo_pago_trabajo"] = "No aplica"
icfes['tipo_pago_trabajo'].value_counts(dropna=False)

tipo_pago_trabajo
No aplica                    293827
Remuneración monetaria       121254
Sin pago                      56663
NaN                           16515
Remuneración no monetaria      8939
Remuneración mixta             7672
Name: count, dtype: int64

### 6. Guardar archivo limpio

In [40]:
from funciones_save_load import guardar_parquet

guardar_parquet(icfes, "icfes_limpio.parquet")

Archivo guardado en la carpeta data con el nombre de icfes_limpio.parquet