## Carga de Datos

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 500)

In [2]:
import sys
from pathlib import Path

# Agregar la carpeta raíz al path para poder importar
carpeta_raiz = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(carpeta_raiz))

# Importar las funciones
from funciones_save_load import guardar_parquet, cargar_parquet

x_train = cargar_parquet("x_train.parquet")
x_test  = cargar_parquet("x_test.parquet")

y_train = cargar_parquet("y_train.parquet")["puntaje_global"]
y_test  = cargar_parquet("y_test.parquet")["puntaje_global"]

In [3]:
x_train

,nacionalidad,pertenece_etnia,estrato_casa,num_personas_casa,cuartos_casa,educacion_padre,educacion_madre,actividad_padre,actividad_madre,internet,tv,computador,lavadora,microndas,carro,moto,consola,num_libros_casa,come_derivados_leche,come_carne_pescado_huevo,come_cereal_frutas_legumbres,cuanto_lee,cuanto_navega_web,horas_trabajo_semanal,colegio_genero,colegio_oficial,colegio_bilingue,tipo_colegio,colegio_urbano_rural,colegio_jornada,edad,educacion_padres,perfil_lector,presento_fuera_edad,region
0,Colombia,No,Estrato 1,7 a 8,Dos,NaN,Tecnico/Tecnologo,Trabajador independiente,Sin actividad remunerada,No,No,No,No,No,No,No,No,11 a 25 libros,3 a 5 veces por semana,Todos o casi todos los días,Todos o casi todos los días,Más de 2 horas,30 minutos o menos,No trabaja,Mixto,Oficial,No,Académico,Urbano,Unica,17.0,Educación Técnica,"Poco Apoyo, Buen Habito",0,Caribe
1,Colombia,No,Estrato 2,3 a 4,Dos,Tecnico/Tecnologo incompleta,NaN,Trabajadores operativos,Trabajadores operativos,Si,Si,Si,Si,No,Si,No,No,11 a 25 libros,Nunca o rara vez comemos eso,1 o 2 veces por semana,1 o 2 veces por semana,30 minutos o menos,Más de 3 horas,No trabaja,Mixto,No oficial,No,Académico,Urbano,Completa,16.0,Educación Superior Incompleta,"Poco Apoyo, Poco Habito",0,Andina
2,Colombia,No,Estrato 2,5 a 6,Dos,Profesional,Profesional,Profesionales,Profesionales,Si,Si,Si,Si,Si,Si,Si,Si,26 a 100 libros,Todos o casi todos los días,Todos o casi todos los días,1 o 2 veces por semana,Entre 1 y 2 horas,Entre 1 y 3 horas,No trabaja,Mixto,No oficial,No,Académico,Urbano,Mañana,17.0,Educación Superior,"Buen Apoyo, Buen Habito",0,Caribe
3,Colombia,No,Estrato 2,3 a 4,Dos,NaN,Tecnico/Tecnologo,Trabajadores operativos,Microempresario,Si,No,Si,Si,No,No,No,No,11 a 25 libros,1 o 2 veces por semana,1 o 2 veces por semana,1 o 2 veces por semana,Entre 1 y 2 horas,Entre 1 y 3 horas,No trabaja,Mixto,Oficial,No,Técnico/académico,Urbano,Completa,17.0,Educación Técnica,"Poco Apoyo, Buen Habito",0,Andina
4,Colombia,No,Estrato 2,3 a 4,Tres,NaN,NaN,Trabajadores operativos,Trabajadores operativos,Si,Si,Si,Si,No,No,No,No,11 a 25 libros,3 a 5 veces por semana,Todos o casi todos los días,1 o 2 veces por semana,30 minutos o menos,Entre 1 y 3 horas,No trabaja,Mixto,Oficial,No,Académico,Urbano,Tarde,17.0,Sin Información,"Poco Apoyo, Poco Habito",0,Andina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403827,Colombia,No,Estrato 3,5 a 6,Tres,NaN,NaN,Trabajadores operativos,Sin actividad remunerada,Si,Si,Si,Si,No,No,No,No,11 a 25 libros,Todos o casi todos los días,3 a 5 veces por semana,1 o 2 veces por semana,No leo por entretenimiento,Más de 3 horas,No trabaja,Mixto,No oficial,No,NaN,Urbano,Mañana,18.0,Sin Información,"Poco Apoyo, Poco Habito",0,Andina
403828,Colombia,No,Estrato 2,3 a 4,Dos,Primaria incompleta,Primaria incompleta,Sector primario,Sector primario,No,No,No,No,Si,No,Si,No,0 a 10 libros,3 a 5 veces por semana,Todos o casi todos los días,1 o 2 veces por semana,30 minutos o menos,30 minutos o menos,Tiempo completo,Mixto,Oficial,No,Técnico/académico,Rural,Sabatina,19.0,Educación Primaria Incompleta,"Poco Apoyo, Poco Habito",0,Andina
403829,Colombia,No,Estrato 1,5 a 6,Dos,NaN,NaN,Microempresario,Microempresario,No,No,No,Si,Si,No,Si,No,0 a 10 libros,1 o 2 veces por semana,1 o 2 veces por semana,1 o 2 veces por semana,30 minutos o menos,Entre 30 y 60 minutos,Trabajo ocasional,Mixto,Oficial,No,Académico,Urbano,Unica,16.0,Sin Información,"Poco Apoyo, Poco Habito",0,Caribe
403830,Colombia,No,Estrato 1,7 a 8,Cinco,NaN,NaN,Directivos,Trabajadores operativos,No,No,Si,No,No,No,No,No,26 a 100 libros,3 a 5 veces por semana,Nunca o rara vez comemos eso,1 o 2 veces por semana,Entre 30 y 60 minutos,Entre 30 y 60 minutos,Trabajo ocasional,Mixto,Oficial,No,Académico,Urbano,Mañana,16.0,Sin Información,"Buen Apoyo, Buen Habito",0,Caribe
403831,Colombia,No,Estrato 1,1 a 2,Tres,Tecnico/Tecnologo,NaN,Trabajador independiente,Microempresario,Si,No,Si,Si,No,No,No,No,0 a 10 libros,Nunca o rara vez comemos eso,1 o 2 veces por semana,Todos o casi todos los días,30 minutos o menos,Más de 3 horas,No trabaja,Mixto,Oficial,No,Técnico/académico,Urbano,Mañana,16.0,Educación Técnica,"Poco Apoyo, Poco Habito",0,Caribe

## 1. Codificar Columnas

In [4]:
x_train.columns

Index(['nacionalidad', 'pertenece_etnia', 'estrato_casa', 'num_personas_casa',
       'cuartos_casa', 'educacion_padre', 'educacion_madre', 'actividad_padre',
       'actividad_madre', 'internet', 'tv', 'computador', 'lavadora',
       'microndas', 'carro', 'moto', 'consola', 'num_libros_casa',
       'come_derivados_leche', 'come_carne_pescado_huevo',
       'come_cereal_frutas_legumbres', 'cuanto_lee', 'cuanto_navega_web',
       'horas_trabajo_semanal', 'colegio_genero', 'colegio_oficial',
       'colegio_bilingue', 'tipo_colegio', 'colegio_urbano_rural',
       'colegio_jornada', 'edad', 'educacion_padres', 'perfil_lector',
       'presento_fuera_edad', 'region'],
      dtype='object')

In [5]:
from utils import codificar_binarias

var_binarias = ['pertenece_etnia', 'internet', 'tv', 'computador', 'lavadora', 'microndas', 'carro', 'moto', 'consola', 'colegio_bilingue']

codificar_binarias(x_train, var_binarias)
codificar_binarias(x_test, var_binarias)

In [6]:
x_train['nacionalidad'] = np.where(x_train['nacionalidad'] == 'Colombia', 1, 0)
x_test['nacionalidad'] = np.where(x_test['nacionalidad'] == 'Colombia', 1, 0)

In [7]:
x_train

,nacionalidad,pertenece_etnia,estrato_casa,num_personas_casa,cuartos_casa,educacion_padre,educacion_madre,actividad_padre,actividad_madre,internet,tv,computador,lavadora,microndas,carro,moto,consola,num_libros_casa,come_derivados_leche,come_carne_pescado_huevo,come_cereal_frutas_legumbres,cuanto_lee,cuanto_navega_web,horas_trabajo_semanal,colegio_genero,colegio_oficial,colegio_bilingue,tipo_colegio,colegio_urbano_rural,colegio_jornada,edad,educacion_padres,perfil_lector,presento_fuera_edad,region
0,1,0,Estrato 1,7 a 8,Dos,NaN,Tecnico/Tecnologo,Trabajador independiente,Sin actividad remunerada,0,0,0,0,0,0,0,0,11 a 25 libros,3 a 5 veces por semana,Todos o casi todos los días,Todos o casi todos los días,Más de 2 horas,30 minutos o menos,No trabaja,Mixto,Oficial,0,Académico,Urbano,Unica,17.0,Educación Técnica,"Poco Apoyo, Buen Habito",0,Caribe
1,1,0,Estrato 2,3 a 4,Dos,Tecnico/Tecnologo incompleta,NaN,Trabajadores operativos,Trabajadores operativos,1,1,1,1,0,1,0,0,11 a 25 libros,Nunca o rara vez comemos eso,1 o 2 veces por semana,1 o 2 veces por semana,30 minutos o menos,Más de 3 horas,No trabaja,Mixto,No oficial,0,Académico,Urbano,Completa,16.0,Educación Superior Incompleta,"Poco Apoyo, Poco Habito",0,Andina
2,1,0,Estrato 2,5 a 6,Dos,Profesional,Profesional,Profesionales,Profesionales,1,1,1,1,1,1,1,1,26 a 100 libros,Todos o casi todos los días,Todos o casi todos los días,1 o 2 veces por semana,Entre 1 y 2 horas,Entre 1 y 3 horas,No trabaja,Mixto,No oficial,0,Académico,Urbano,Mañana,17.0,Educación Superior,"Buen Apoyo, Buen Habito",0,Caribe
3,1,0,Estrato 2,3 a 4,Dos,NaN,Tecnico/Tecnologo,Trabajadores operativos,Microempresario,1,0,1,1,0,0,0,0,11 a 25 libros,1 o 2 veces por semana,1 o 2 veces por semana,1 o 2 veces por semana,Entre 1 y 2 horas,Entre 1 y 3 horas,No trabaja,Mixto,Oficial,0,Técnico/académico,Urbano,Completa,17.0,Educación Técnica,"Poco Apoyo, Buen Habito",0,Andina
4,1,0,Estrato 2,3 a 4,Tres,NaN,NaN,Trabajadores operativos,Trabajadores operativos,1,1,1,1,0,0,0,0,11 a 25 libros,3 a 5 veces por semana,Todos o casi todos los días,1 o 2 veces por semana,30 minutos o menos,Entre 1 y 3 horas,No trabaja,Mixto,Oficial,0,Académico,Urbano,Tarde,17.0,Sin Información,"Poco Apoyo, Poco Habito",0,Andina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403827,1,0,Estrato 3,5 a 6,Tres,NaN,NaN,Trabajadores operativos,Sin actividad remunerada,1,1,1,1,0,0,0,0,11 a 25 libros,Todos o casi todos los días,3 a 5 veces por semana,1 o 2 veces por semana,No leo por entretenimiento,Más de 3 horas,No trabaja,Mixto,No oficial,0,NaN,Urbano,Mañana,18.0,Sin Información,"Poco Apoyo, Poco Habito",0,Andina
403828,1,0,Estrato 2,3 a 4,Dos,Primaria incompleta,Primaria incompleta,Sector primario,Sector primario,0,0,0,0,1,0,1,0,0 a 10 libros,3 a 5 veces por semana,Todos o casi todos los días,1 o 2 veces por semana,30 minutos o menos,30 minutos o menos,Tiempo completo,Mixto,Oficial,0,Técnico/académico,Rural,Sabatina,19.0,Educación Primaria Incompleta,"Poco Apoyo, Poco Habito",0,Andina
403829,1,0,Estrato 1,5 a 6,Dos,NaN,NaN,Microempresario,Microempresario,0,0,0,1,1,0,1,0,0 a 10 libros,1 o 2 veces por semana,1 o 2 veces por semana,1 o 2 veces por semana,30 minutos o menos,Entre 30 y 60 minutos,Trabajo ocasional,Mixto,Oficial,0,Académico,Urbano,Unica,16.0,Sin Información,"Poco Apoyo, Poco Habito",0,Caribe
403830,1,0,Estrato 1,7 a 8,Cinco,NaN,NaN,Directivos,Trabajadores operativos,0,0,1,0,0,0,0,0,26 a 100 libros,3 a 5 veces por semana,Nunca o rara vez comemos eso,1 o 2 veces por semana,Entre 30 y 60 minutos,Entre 30 y 60 minutos,Trabajo ocasional,Mixto,Oficial,0,Académico,Urbano,Mañana,16.0,Sin Información,"Buen Apoyo, Buen Habito",0,Caribe
403831,1,0,Estrato 1,1 a 2,Tres,Tecnico/Tecnologo,NaN,Trabajador independiente,Microempresario,1,0,1,1,0,0,0,0,0 a 10 libros,Nunca o rara vez comemos eso,1 o 2 veces por semana,Todos o casi todos los días,30 minutos o menos,Más de 3 horas,No trabaja,Mixto,Oficial,0,Técnico/académico,Urbano,Mañana,16.0,Educación Técnica,"Poco Apoyo, Poco Habito",0,Caribe

In [8]:
from utils import codificar_one_hot_minusculas

cols = ["estrato_casa", "num_personas_casa", 'cuartos_casa', 'educacion_padre', 'educacion_madre', 'actividad_padre',
       'actividad_madre', 'num_libros_casa', 'come_derivados_leche', 'come_carne_pescado_huevo', 'come_cereal_frutas_legumbres', 
       'cuanto_lee', 'cuanto_navega_web', 'horas_trabajo_semanal', 'colegio_genero', 'colegio_oficial', 'tipo_colegio', 'colegio_urbano_rural',
       'colegio_jornada', 'educacion_padres', 'perfil_lector', 'region']

codificar_one_hot_minusculas(x_train, cols, dummy_na=True)
codificar_one_hot_minusculas(x_test, cols, dummy_na=True)

x_train

,nacionalidad,pertenece_etnia,internet,tv,computador,lavadora,microndas,carro,moto,consola,colegio_bilingue,edad,presento_fuera_edad,estrato_casa_estrato 1,estrato_casa_estrato 2,estrato_casa_estrato 3,estrato_casa_estrato 4,estrato_casa_estrato 5,estrato_casa_estrato 6,estrato_casa_sin estrato,estrato_casa_nan,num_personas_casa_1 a 2,num_personas_casa_3 a 4,num_personas_casa_5 a 6,num_personas_casa_7 a 8,num_personas_casa_9 o más,num_personas_casa_nan,cuartos_casa_cinco,cuartos_casa_cuatro,cuartos_casa_dos,cuartos_casa_seis o mas,cuartos_casa_tres,cuartos_casa_uno,cuartos_casa_nan,educacion_padre_ninguna,educacion_padre_no aplica,educacion_padre_primaria,educacion_padre_primaria incompleta,educacion_padre_profesional,educacion_padre_profesional incompleta,educacion_padre_tecnico/tecnologo,educacion_padre_tecnico/tecnologo incompleta,educacion_padre_nan,educacion_madre_ninguna,educacion_madre_no aplica,educacion_madre_primaria,educacion_madre_primaria incompleta,educacion_madre_profesional,educacion_madre_profesional incompleta,educacion_madre_tecnico/tecnologo,educacion_madre_tecnico/tecnologo incompleta,educacion_madre_nan,actividad_padre_directivos,actividad_padre_microempresario,actividad_padre_pensionado,actividad_padre_profesionales,actividad_padre_sector primario,actividad_padre_sin actividad remunerada,actividad_padre_sin informacion,actividad_padre_trabajador independiente,actividad_padre_trabajadores operativos,actividad_padre_nan,actividad_madre_directivos,actividad_madre_microempresario,actividad_madre_pensionado,actividad_madre_profesionales,actividad_madre_sector primario,actividad_madre_sin actividad remunerada,actividad_madre_sin informacion,actividad_madre_trabajador independiente,actividad_madre_trabajadores operativos,actividad_madre_nan,num_libros_casa_0 a 10 libros,num_libros_casa_11 a 25 libros,num_libros_casa_26 a 100 libros,num_libros_casa_más de 100 libros,num_libros_casa_nan,come_derivados_leche_1 o 2 veces por semana,come_derivados_leche_3 a 5 veces por semana,come_derivados_leche_nunca o rara vez comemos eso,come_derivados_leche_todos o casi todos los días,come_derivados_leche_nan,come_carne_pescado_huevo_1 o 2 veces por semana,come_carne_pescado_huevo_3 a 5 veces por semana,come_carne_pescado_huevo_nunca o rara vez comemos eso,come_carne_pescado_huevo_todos o casi todos los días,come_carne_pescado_huevo_nan,come_cereal_frutas_legumbres_1 o 2 veces por semana,come_cereal_frutas_legumbres_3 a 5 veces por semana,come_cereal_frutas_legumbres_nunca o rara vez comemos eso,come_cereal_frutas_legumbres_todos o casi todos los días,come_cereal_frutas_legumbres_nan,cuanto_lee_30 minutos o menos,cuanto_lee_entre 1 y 2 horas,cuanto_lee_entre 30 y 60 minutos,cuanto_lee_más de 2 horas,cuanto_lee_no leo por entretenimiento,cuanto_lee_nan,cuanto_navega_web_30 minutos o menos,cuanto_navega_web_entre 1 y 3 horas,cuanto_navega_web_entre 30 y 60 minutos,cuanto_navega_web_más de 3 horas,cuanto_navega_web_no navega internet,cuanto_navega_web_nan,horas_trabajo_semanal_medio tiempo,horas_trabajo_semanal_no trabaja,horas_trabajo_semanal_tiempo completo,horas_trabajo_semanal_tiempo parcial reducido,horas_trabajo_semanal_trabajo ocasional,horas_trabajo_semanal_nan,colegio_genero_femenino,colegio_genero_masculino,colegio_genero_mixto,colegio_genero_nan,colegio_oficial_no oficial,colegio_oficial_oficial,colegio_oficial_nan,tipo_colegio_académico,tipo_colegio_no aplica,tipo_colegio_técnico,tipo_colegio_técnico/académico,tipo_colegio_nan,colegio_urbano_rural_rural,colegio_urbano_rural_urbano,colegio_urbano_rural_nan,colegio_jornada_completa,colegio_jornada_mañana,colegio_jornada_noche,colegio_jornada_sabatina,colegio_jornada_tarde,colegio_jornada_unica,colegio_jornada_nan,educacion_padres_educación primaria,educacion_padres_educación primaria incompleta,educacion_padres_educación superior,educacion_padres_educación superior incompleta,educacion_padres_educación técnica,educacion_padres_no aplica,educacion_padres_sin educación formal,educacion_padres_sin información,educacion_padres_nan,"perfil_lector_buen apoyo, buen habito","perfil_lector_buen apoyo, poco habito",perfil_lector_desconocido,"perfil_lector_poco apoyo, buen habito","perfil_lector_poco apoyo, poco habito",perfil_lector_nan,region_amazónica,region_andina,region_caribe,region_orinoquía,region_pacífica,region_nan
0,1,0,0,0,0,0,0,0,0,0,0,17.0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
1,1,0,1,1,1,1,0,1,0,0,0,16.0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
2,1,0,1,1,1,1,1,1,1,1,0,17.0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0
3,1,0,1,0,1,1,0,0,0,0,0,17.0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
4,1,0,1,1,1,1,0,0,0,0,0,17.0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403827,1,0,1,1,1,1,0,0,0,0,0,18.0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0
403828,1,0,0,0,0,0,1,0,1,0,0,19.0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
403829,1,0,0,0,0,1,1,0,1,0,0,16.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0
403830,1,0,0,0,1,0,0,0,0,0,0,16.0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0
403831,1,0,1,0,1,1,0,0,0,0,0,16.0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0

In [9]:
x_test

,nacionalidad,pertenece_etnia,internet,tv,computador,lavadora,microndas,carro,moto,consola,colegio_bilingue,edad,presento_fuera_edad,estrato_casa_estrato 1,estrato_casa_estrato 2,estrato_casa_estrato 3,estrato_casa_estrato 4,estrato_casa_estrato 5,estrato_casa_estrato 6,estrato_casa_sin estrato,estrato_casa_nan,num_personas_casa_1 a 2,num_personas_casa_3 a 4,num_personas_casa_5 a 6,num_personas_casa_7 a 8,num_personas_casa_9 o más,num_personas_casa_nan,cuartos_casa_cinco,cuartos_casa_cuatro,cuartos_casa_dos,cuartos_casa_seis o mas,cuartos_casa_tres,cuartos_casa_uno,cuartos_casa_nan,educacion_padre_ninguna,educacion_padre_no aplica,educacion_padre_primaria,educacion_padre_primaria incompleta,educacion_padre_profesional,educacion_padre_profesional incompleta,educacion_padre_tecnico/tecnologo,educacion_padre_tecnico/tecnologo incompleta,educacion_padre_nan,educacion_madre_ninguna,educacion_madre_no aplica,educacion_madre_primaria,educacion_madre_primaria incompleta,educacion_madre_profesional,educacion_madre_profesional incompleta,educacion_madre_tecnico/tecnologo,educacion_madre_tecnico/tecnologo incompleta,educacion_madre_nan,actividad_padre_directivos,actividad_padre_microempresario,actividad_padre_pensionado,actividad_padre_profesionales,actividad_padre_sector primario,actividad_padre_sin actividad remunerada,actividad_padre_sin informacion,actividad_padre_trabajador independiente,actividad_padre_trabajadores operativos,actividad_padre_nan,actividad_madre_directivos,actividad_madre_microempresario,actividad_madre_pensionado,actividad_madre_profesionales,actividad_madre_sector primario,actividad_madre_sin actividad remunerada,actividad_madre_sin informacion,actividad_madre_trabajador independiente,actividad_madre_trabajadores operativos,actividad_madre_nan,num_libros_casa_0 a 10 libros,num_libros_casa_11 a 25 libros,num_libros_casa_26 a 100 libros,num_libros_casa_más de 100 libros,num_libros_casa_nan,come_derivados_leche_1 o 2 veces por semana,come_derivados_leche_3 a 5 veces por semana,come_derivados_leche_nunca o rara vez comemos eso,come_derivados_leche_todos o casi todos los días,come_derivados_leche_nan,come_carne_pescado_huevo_1 o 2 veces por semana,come_carne_pescado_huevo_3 a 5 veces por semana,come_carne_pescado_huevo_nunca o rara vez comemos eso,come_carne_pescado_huevo_todos o casi todos los días,come_carne_pescado_huevo_nan,come_cereal_frutas_legumbres_1 o 2 veces por semana,come_cereal_frutas_legumbres_3 a 5 veces por semana,come_cereal_frutas_legumbres_nunca o rara vez comemos eso,come_cereal_frutas_legumbres_todos o casi todos los días,come_cereal_frutas_legumbres_nan,cuanto_lee_30 minutos o menos,cuanto_lee_entre 1 y 2 horas,cuanto_lee_entre 30 y 60 minutos,cuanto_lee_más de 2 horas,cuanto_lee_no leo por entretenimiento,cuanto_lee_nan,cuanto_navega_web_30 minutos o menos,cuanto_navega_web_entre 1 y 3 horas,cuanto_navega_web_entre 30 y 60 minutos,cuanto_navega_web_más de 3 horas,cuanto_navega_web_no navega internet,cuanto_navega_web_nan,horas_trabajo_semanal_medio tiempo,horas_trabajo_semanal_no trabaja,horas_trabajo_semanal_tiempo completo,horas_trabajo_semanal_tiempo parcial reducido,horas_trabajo_semanal_trabajo ocasional,horas_trabajo_semanal_nan,colegio_genero_femenino,colegio_genero_masculino,colegio_genero_mixto,colegio_genero_nan,colegio_oficial_no oficial,colegio_oficial_oficial,colegio_oficial_nan,tipo_colegio_académico,tipo_colegio_no aplica,tipo_colegio_técnico,tipo_colegio_técnico/académico,tipo_colegio_nan,colegio_urbano_rural_rural,colegio_urbano_rural_urbano,colegio_urbano_rural_nan,colegio_jornada_completa,colegio_jornada_mañana,colegio_jornada_noche,colegio_jornada_sabatina,colegio_jornada_tarde,colegio_jornada_unica,colegio_jornada_nan,educacion_padres_educación primaria,educacion_padres_educación primaria incompleta,educacion_padres_educación superior,educacion_padres_educación superior incompleta,educacion_padres_educación técnica,educacion_padres_no aplica,educacion_padres_sin educación formal,educacion_padres_sin información,educacion_padres_nan,"perfil_lector_buen apoyo, buen habito","perfil_lector_buen apoyo, poco habito",perfil_lector_desconocido,"perfil_lector_poco apoyo, buen habito","perfil_lector_poco apoyo, poco habito",perfil_lector_nan,region_amazónica,region_andina,region_caribe,region_orinoquía,region_pacífica,region_nan
0,1,0,1,1,1,1,0,0,0,0,0,17.0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0
1,1,0,1,1,1,1,0,0,0,0,0,23.0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
2,1,0,1,1,1,1,1,0,1,1,0,16.0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
3,1,0,1,1,0,0,0,1,0,0,0,17.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
4,1,0,1,1,0,1,1,0,0,0,0,17.0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100953,1,1,0,0,0,0,0,0,1,0,0,18.0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
100954,1,0,1,1,0,1,1,0,1,0,0,16.0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
100955,1,1,0,1,0,1,1,0,0,0,0,19.0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
100956,1,0,0,0,0,1,0,0,0,0,0,16.0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
100957,1,0,1,1,1,1,1,0,0,0,0,20.0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0

## 2. Entrenando el Primer Modelo